### ISSUE TITLE
Pullback og pushout

### ISSUE THREAD

**Issue by jfremstad** [jfremstad/matematisk_ordliste#1]
**Denne diskusjonstråden er flyttet fra en tidligere versjon av prosjektsidene. Se øverst i hver kommentar for å finne ut hvem som opprinnelig skrev hvert enkelt innlegg.**

Fra @jfremstad:
Både *pullback* og *pushout* er i hvert fall veldig etablert på NTNU, samtidig som jeg ikke ser en naturlig og god oversettelse. Jeg vet at noen av [datatermene](http://www.sprakradet.no/sprakhjelp/Skriverad/Ordlister/Datatermar) som brukes er "pullteknologi" og "pushteknologi".

**Comment by jfremstad** [comment]
Svar fra @johahaug:
Forslag kan jo være "tilbaketrekning" og "framskyvning" eller noe lignende, men du har nok rett i at de fleste faglige ansatte vil oppfatte dette som kronglete og bare vil fortsette å si *pullback* og *pushout* slik som de gjør i dag.

Dette dreier seg vel egentlig om et mer generelt spørsmål, nemlig hvordan vi skal forholde oss til termer der det er dårlige oversettelser som allerede er i svært utstrakt bruk. Skal vi i slike tilfeller akseptere at det på et tidspunkt er innført en dårlig oversettelse som nå er i allmenn bruk og videreføre denne? Eller skal vi forsøke å finne en bedre oversettelse og risikere at denne ikke kommer til å bli tatt i bruk?

Jeg kjenner jeg stiller meg litt skeptisk til å ta med virkelig dårlige oversettelser i ordlista, da jeg tenker det til en viss grad signaliserer at det er "greit" å bare bruke det engelske ordet også på norsk. Samtidig er jeg enig i at det at oversettelser som starter med "pull" og "push" er tatt med i datatermene, kan brukes som et argument for å gjøre noe lignende her.

**Comment by jfremstad** [comment]
Svar fra @olevaage:
Det er en vanskelig nøtt. Det er likevel en forskjell mellom pullback/pushout og pullteknologi/pushteknologi. Etterleddet i det to datatermene er lett å forstå og ikke minst å bøye. En nærmere parallell ville være pullbackXXX og pushoutXXX, der XXX står for hva det egentlig er snakk om, altså overbegrepet. Er det pullbacktransport/pushouttransport, pullbackutregning/pushoututregning, pullbackkategori/pushoutkategori osv.? Jeg kjenner ikke faget, så det er vanskelig for meg å vurdere kandidater her.

Om dere ønsker å føre opp en slik langform, kan kortformene være henholdsvis pullback og pushout. Det er en ganske pragmatisk tilnærming.

En annen mulighet er å benytte sjansen til å lage et selvforklarende ord på norsk, og det kunne nok være tilbaketrekning og framskyvning (ev. tilbaketrekningXXX og framskyvningXXX, om man vil legge på et forklarende etterledd/overbegrep.)

Innenfor fjernsynsteknikk har man også begrepet pushout. Der har man valgt kameratilbaketrekking som norsk ord. Her er det forleddet (kamera-) som spesifiserer hva det dreier seg om, dvs. omvendt av det jeg foreslår ovenfor. Det er også en mulighet. Her er det bare å drodle for å finne et mer selvforklarende ord.

Samtidig ligger det et grunnleggende spørsmål her. Som dere skriver, skal ordboka være beskrivende eller normativ. I praksis er de fleste ordbøker et sted imellom.

**Comment by jfremstad** [comment]
Svar fra @johahaug:
@bervinator har sett nærmere på hvordan man oversetter dette på fransk, og vi vil se på om det kan være mulig å gjøre noe tilsvarende på norsk. I tillegg hadde det vært en fordel om vi også kunne begynne å se på ord som pushforward og pullback fra andre områder f.eks. fra mangfoldigheter eller målteori (?) og bestemme oss for oversettelser av alle beslektede termer samtidig. Fint om alle leser gjennom det som er skrevet i denne tråden fra før, så vi har det som grunnlag for videre drøfting.

**Comment by jfremstad** [comment]
Svar fra @bervinator:
Franskmenn insisterer på å bruke ordene *produit fibré* og *somme amalgamée* for disse termene. Dette gir fullstendig mening i topologisk sammenheng, men når det kommer til generaliseringene i kategoriteorien er det mer rom for fleksibilitet. Personlig foretrekker jeg "fibrert produkt" og "fibrert koprodukt" på norsk (ettersom de faktisk er produkt/koprodukter i en ny kategori bestående av morfier med felles domene/kodomene), men jeg formoder at et mindretall av norske matematikere tar disse i bruk.

En annen grunn til å unngå "pullback(diagram)" i denne sammenhengen er å skille det fra tilbaketrekning av vektorfelt, mål, o.l. Jeg ser ingen grunn til at dette skal være et spesialtilfelle av (det jeg liker å kalle) fibrerte produkt (om jeg ikke tar helt feil, er tilbaketrekningen en funktor, og ikke en grense). Isåfall burde "pushforward" og "pushout" blitt kalt det samme. Nærmere inspeksjon er planlagt.

**Comment by jfremstad** [comment]
Svar fra @qeeku:
Det man i målteori kaller *pushforward measure* kalles også *image measure*. Selv om en naturlig oversettelse av sistnevnte vil være «bildemål», er jeg ikke helt overbevist om at dette burde brukes uten videre granskning: det induserte målet kan eksistere på en sigma-algebra i en mengde som strengt inneholder bildet av funksjonen som fremskyver strukturen, dersom denne ikke skulle være surjektiv.

**Comment by sorengam** [comment]
For å unngå de kronglete ordene  "tilbaketrekning" og "framskyvning", er det kanskje en mulighet med "baktrekk" og "utskyv"/"utdytt"? De har i hvert fall to stavelser hver, som de engelske termene. Men jeg kan ikke si å ha hørt disse oversettelsene i bruk. 

En omskrivning av "fibrert produkt" som jeg har hørt ofte, er "fiberprodukt". Oversettelsen "fiberkoprodukt" mener jeg også å ha hørt.

**Comment by bervinator** [comment]
Språkrådet mener at pullback- og pushoutkvadrat er lovlige. Disse legges inn i ordlisten. Den beslektede termen fiberprodukt kommer også med. Tråden lukkes trolig 25. februar.
