### ISSUE TITLE
concave, cyclic, cyclic group

### ISSUE THREAD

**Issue by StineBerge** [jfremstad/matematisk_ordliste#10]
**Forslag:**

- [x] konkav, konkav, concave 
- [x] syklisk, syklisk, cyclic 
- [x] syklisk gruppe, syklisk gruppe, cyclic group

**Merknad:**
Kan også oversette "syklisk" med "tilbakevendende".

**Comment by johahaug** [comment]
Takk for mange bra forslag til oversettelser, både her og i andre tråder! Jeg er enig i alle de tre termene som er foreslått i dette innlegget. 

Når det gjelder oppføring av ordklasse: Hittil har vi tenkt at det er nødvendig å føre opp dette kun i tilfeller der det i utgangspunktet er uklart hvilken ordklasse det er snakk om. F.eks. har oppslagsordene

```
  metrikk,metrikk,metric,"Ordklasse: substantiv"
  metrisk,metrisk,metric,"Ordklasse: adjektiv"
  ```

en merknad om ordklasse på grunn av sammenfall på engelsk. Jeg synes det vil være en ulempe å legge inn merknad om ordklasse på alle oppslagsord, da dette vil føre til at man alltid får en grønn pluss og at denne som oftest leder til ganske "uinteressant" informasjon. Jeg tror det er bedre at det er lagt inn merknader først og fremst i tilfeller der den supplerende informasjonen er _viktig_, slik at brukerne ikke venner seg til at det ikke er noe "vits" i å trykke på den grønne knappen. Jeg foreslår derfor at vi ikke har noen merknad om ordklasse i disse tre tilfellene. 

Angående tilbakevendende: Jeg synes dette ville være en innholdsmessig flott oversettelse, men må innrømme jeg selv aldri har sett eller hørt denne oversettelsen i bruk. Vet du om det finnes noen som faktisk bruker den?

**Comment by johahaug** [comment]
Jeg liker også tanken på å kalle det tilbakevendende generator, siden det på mange måter gir bedre forståelse for begrepet. Det går kanskje an å vurdere å legge det inn som synonym.
