### ISSUE TITLE
Flerpartsberegning

### ISSUE THREAD

**Issue by magnudr** [jfremstad/matematisk_ordliste#100]
**Forslag:**
Flerpartsberegning, Fleirpartsberekning, Multi-party computation

**Comment by bervinator** [comment]
Denne foreslås på neste verifiseringsmøte. 
mvh Erlend

**Comment by bervinator** [comment]
Denne termen har blitt diskutert og er nå på vei inn i ordlisten.
Mange takk for innspill!
