### ISSUE TITLE
Singleton

### ISSUE THREAD

**Issue by danielKSt** [jfremstad/matematisk_ordliste#106]
**Kommentar**
Veit ikkje kva som er eit passande norsk ord for mengdar med eit element, men det dukker opp nokså ofte, så det hadde vore greit å ha ei oversettjing.

**Comment by bervinator** [comment]
Denne termen er på vei inn i ordlisten.
Mange takk for innspill!
Kommenter gjerne navn og evt. utdanningsinstitusjon, slik at vi kan legge deg til som bidragsyter.

**Comment by danielKSt** [comment]
Flott å høyre! Eitpunktsmengde høyres ut som ei fornuftig oversetjing. 

Eg heite Daniel Kjellevold Steinsland, og er student på NTNU :)

**Comment by bervinator** [comment]
Du er lagt til som bidragsyter, og termer dukker opp i ordlisten om noen dager.
Takk!
