### ISSUE TITLE
WLOG / without loss of generality

### ISSUE THREAD

**Issue by rknb** [jfremstad/matematisk_ordliste#109]
Noen idéer om hvordan man kan oversette dette?

**Comment by bervinator** [comment]
Søket "uten tap av generalitet" får bokstavelig talt [hundrevis av treff på Bokhylla ](https://www.nb.no/search?q=%22uten%20tap%20av%20generalitet%22&mediatype=b%C3%B8ker), publisert mellom 1955 og 2020. Nynorskvarianten "utan tap av generalitet" gir to utgaver av samme bok, men jeg lurer på om generalitet ikke er lovlig på nynorsk.

**Comment by bervinator** [comment]
Denne termen videresendes til prosjektgruppen. Jeg tviler på at de hindres i sin ferd til ordlisten. Tråden lukkes. 
Mange takk for forslag!
