### ISSUE TITLE
Möbius transformation, biholomorphic functon, biholomorphism, linear fractional transformation (kompleks analyse)

### ISSUE THREAD

**Issue by StineBerge** [jfremstad/matematisk_ordliste#11]
**Forslag:**

- [x] möbiustransformasjon, möbiustransformasjon, Möbius transformation
- [x] biholomorf funksjon, biholomorf funksjon, biholomorphic function
- [x] biholomorfi, biholomorfi, biholomorphism
- [x] lineærbrøktransformasjon, lineærbrøktransformasjon, linear fractional transformation

**Comment by jfremstad** [comment]
Takk! Jeg regner med du mener *biholomo**r**f funksjon* på både bokmål og nynorsk, og *biholomorphic funct**i**on* på engelsk.

Kan *biholomorfi* og *biholomorf funksjon* listes opp som synonymer?

**Comment by StineBerge** [comment]
Takk for rettelsen.

Ja, så lenge det samme blir gjort for holomorf funksjon så er jeg fornøyd.
