### ISSUE TITLE
Perspektivitet

### ISSUE THREAD

**Issue by TorgunnKarolineMoe** [jfremstad/matematisk_ordliste#110]
**Forslag:**
perspektivitet, perspektivitet, perspectivity

**Merknad:**

**Kommentar:**

**Comment by bervinator** [comment]
Denne kan fint bli med i ordlisten. Vi verifiserer denne termen (sannsynligvis uten motstand) i januar.
Kommenter gjerne navn og evt. utdanningsinstitusjon, slik at vi kan legge deg til som bidragsyter.

**Comment by bervinator** [comment]
Termen videresendes til prosjektgruppen. Jeg tviler på at de hindres i sin ferd til ordlisten. Tråden lukkes. 
Mange takk for forslag!
