### ISSUE TITLE
Kryssledd

### ISSUE THREAD

**Issue by fishyFrogFace** [jfremstad/matematisk_ordliste#111]
kryssledd, kryssledd, cross product terms

Jeg er ikke matematiker, dette var noe som dukket opp i et introfag i lineær algebra.

**Comment by bervinator** [comment]
Denne har ikke vi tenkt på!
Vi verifiserer denne termen i januar.
Jeg tror jeg ville ha ført opp "cross term" på engelsk, ettersom det ikke har noe med kryssproduktet å gjøre. 
Kommenter gjerne navn og evt. utdanningsinstitusjon, slik at vi kan legge deg til som bidragsyter.

**Comment by fishyFrogFace** [comment]
Mitt navn er Camilla Rygh. Begrepet "kryssledd" fant jeg her (oppg. 8b): https://www.math.ntnu.no/emner/MA1201/2019h/VO/MA1201eks2020K.pdf
Det engelske fant jeg i boka **"Howard Anton, Chris Rorres, Anton Kaul: Elementary Linear Algebra, Applications Version, 12th Edition"** på side 420: _"Furthermore, if b=0 in (8), then there is no cross product term (i.e., term involving xy)..."_.

**Comment by bervinator** [comment]
Termen kryssledd videresendes til prosjektgruppen. Jeg tviler på at de hindres i sin ferd til ordlisten. Tråden lukkes. 
Mange takk for forslag!
