### ISSUE TITLE
Gauge

### ISSUE THREAD

**Issue by kklocker** [jfremstad/matematisk_ordliste#113]
**Forslag:**
justering, justering, gauge
justertransformasjon, justertransformasjon, gauge transformation
justerinvarians, justerinvarians, gauge invariance
etc...

**Kommentar**
Vet ikke om dette er mest relevant for fysikere, men det er flere wiki-artikler som forklarer matten:
[Wikipedia: Gauge symmetry](https://en.wikipedia.org/wiki/Gauge_symmetry_(mathematics))
[Wikipedia: Gauge group](https://en.wikipedia.org/wiki/Gauge_group_(mathematics))

Forslaget mitt er å følge konvensjonen fra side 236-237 i Hemmer, Per Chr. Kvantemekanikk. Tapir akademisk, 2005:

- Gauge -> justering
- Gauge transformation -> justertransformasjon

**Comment by petfly** [comment]
Hei,

Jeg liker dette forslaget. Har jobbet litt med ordet gauge, og ikke funnet noe tilfredsstillende, men Hemmer er jo en veldig god autoritet, i alle fall for fysikere på NTNU. Justering er muligens også så nærme man kommer en god oversettelse. Det eneste negative er at justering muligens faller litt i kategorien "ord som ikke burde gis fast definisjon", fordi de kan tenkes å brukes upresist, gauge er jo derimot helt entydig. Men jeg skal huske det.

**Comment by kklocker** [comment]
Jeg er litt enig i den ulempen, og er mye mer komfortabel med de sammensatte ordene (justertransformasjon, invarians) enn justering som selvstendig definisjon.

**Comment by bervinator** [comment]
Termene justering, justertransformasjon og justerinvarians videresendes til prosjektgruppen. Jeg tviler på at de hindres i sin ferd til ordlisten. Tråden lukkes. 
Mange takk for forslag!
