### ISSUE TITLE
Signed Distance Function / Field

### ISSUE THREAD

**Issue by pbsds** [jfremstad/matematisk_ordliste#114]
**Kommentar**
For dette uttrykket er det viktig å formidle at fortegnet er betydelig. 
'Avstandsfunksjon' og 'avstandsfelt' beskriver ikke konseptet.

**Comment by bervinator** [comment]
Takk for forslag!
Det er mulig jeg stiller et dumt spørsmål nå, men hva er det som skiller en avstandsfunksjon fra en metrikk?

**Comment by pbsds** [comment]
Vil anta en metrikk er for måle avstanden, mens en avstandsfunkjon   'spør' om avstanden

**Comment by pbsds** [comment]
Tror ikke vi har en godt definert måte å skille de på, ettersom ordene brukes litt om hverandre.
For meg vil en intuitiv måte å skille mellom de er at den ene *måler/beregner* en avstand ut fra argumentene og det å *spør* om avstanden. Så en metrikk kan da f.eks. være basert på to koordinater som argument mens en avstandsfunksjon kun tar inn ett?

**Comment by danielKSt** [comment]
Kan man kalle det for ein orientert avstandsfunksjon kanskje? Slik eg forstår det tar ein orientert avstandsfunksjon inn ein undermengde, X, av eit metrisk rom ,V, og eit element, x, av dette metriske rommet. Og returnerer avstanden mellom randen av X og elementet x, der forteiknet til resultatet blir negativt om x ikkje er inneholdt i X, og positivt dersom x er inneholdt i X.

**Comment by danielKSt** [comment]
Har snakka litt om dette med nokon andre, og då kom me fram til at me likte "retta avstandsfunksjon" betre enn "orientert avstandsfunksjon", mest fordi det er enklare å seie, men eg føler begge deler klart formidler at fortegnet er viktig :)

**Comment by bervinator** [comment]
Begge kan fungere. 
Jeg skal forhøre meg med fagpersoner om hva de bruker.

**Comment by bervinator** [comment]
Ingen av fagpersonene jeg har vært i kontakt med har sterke meninger om hva dette burde kalles på norsk.
Tidligere har vi oversatt _signed measure_ til fortegnsmål. Jeg tror fortegnsmetrikk kan fungerere for _signed metric_, men fortegnsavstandsfunksjon blir kanskje for mye av det gode.

**Comment by bervinator** [comment]
Termene fortegnsmetrikk og avstandsfunksjon videresendes til prosjektgruppen. Jeg tviler på at de hindres i sin ferd til ordlisten. Tråden lukkes. 
Mange takk for forslag!
