### ISSUE TITLE
Meet/join

### ISSUE THREAD

**Issue by johahaug** [jfremstad/matematisk_ordliste#115]
I forbindelse med gitter (engelsk lattice) snakker man ofte om "meet" og "join". Er det noen som vet hva disse burde oversettes til på norsk? Jeg ser at de ikke ligger i ordlista.

**Comment by dilawarm** [comment]
Kanskje hente inspirasjon fra dansk wikipedia-side om gitter: https://da.wikipedia.org/wiki/Gitter_(ordning)

**Comment by bervinator** [comment]
Hva med å kalle disse minste øvre / største nedre skranke, der konteksten presiseres i en merknad? En gitterordning er en delvis ordnet mengde der disse eksisterer, og jeg er usikker på om det finnes bedre alternativ på norsk (men jeg har et åpent sinn). Avledede termer som "join-irreducible" kan bli litt tunge. Her kan vi for eksempel bruke sup-irredusbel for å spare på stavelsene.

Neste verifiseringsmøte er om to uker. Se ikke bort ifra at disse diskuteres.

________________________________

**Comment by johahaug** [comment]
Jeg synes umiddelbart at dette høres rimelig ut. Enig i at det er viktig med merknad om kontekst her.

**Comment by bervinator** [comment]
Disse termene videresendes til prosjektgruppen. Jeg tviler på at de hindres i sin ferd til ordlisten. Tråden lukkes. 
Mange takk for forslag!
