### ISSUE TITLE
Coercive

### ISSUE THREAD

**Issue by danielKSt** [jfremstad/matematisk_ordliste#116]
Dette begrepet dukker stadig opp, og eg finn det ikkje i ordlista, eg reffererer då til [dette](https://en.wikipedia.org/wiki/Coercive_function) . Eg høyrer det ofte sagt ganske direkte som "koersiv", personeleg er eg ikkje kjempeglad i denne enkle fornorskinga av det engelske uttrykket. Men eg har ikkje noko gode forslag til korleis det bør omsettjast. Eg har kanskje tenkt at det kunne funke med noko som "nedad tvungen", eller "tvungen nedenfra". Dette er på mange måtar meir beskrivande iallefall. Disse er også litt tyngre å seie enn "koersiv", så der veit eg ikkje om eg faktisk likar desse bedre.

**Comment by bervinator** [comment]
Hei og takk for forslag! Vi diskuterte akkurat denne termen på siste verifiseringsmøte. Vi kom frem til at koersiv var en grei oversettelse, men ser nærmere på dine forslag om snaue to uker.

**Comment by bervinator** [comment]
De snaue to ukene har gått. Det viser seg at termen vi diskuterte blir brukt i en litt annen sammenheng.
Under neste verifiseringsmøte foreslås både koersiv og tvungen nedenfra.
