### ISSUE TITLE
Algebraisk tallteori

### ISSUE THREAD

**Issue by markusvhagen** [jfremstad/matematisk_ordliste#118]
**Forslag:**
regulator, regulator, regulator
ramifisere, ramifisere, ramify
tallenes geometri, talane sin geometri, geometry of numbers
minkowskibegrensningen, minkowskibegrensinga, (the) Minkowski bound
fundamentalenheten, fundamentalenheten, fundamental unit
klassetallsformelen, klassetalformelen, class number formula
dirichletkarakter, dirichletkarakter, Dirichlet character
Dedekinds zetafunksjon, Dedekind sin zetafunksjon, Dedekind's zeta function

**Kommentar:**
Usikker på nynorsk oversettelse på en del av forslagene.

**Comment by bervinator** [comment]
Mange takk for forslag!
Jeg sjekker opp nynorsken og foreslår termene på et verifiseringsmøte like før påske.

**Comment by viktoba** [comment]
Hei!

Jeg skrev noe lignende i tråden “To hundre forslag, og ...”,  men kommenterer igjen her, siden ordet “ramify” dukket opp igjen. 

“Ramification” betyr forgrening, og kommer fra latin “ramus”, som betyr gren. På tysk brukes "Verzweigung", som nettopp betyr "forgrening". (“Zweig” betyr “gren”). 

Jeg vil påstå at ordet “forgrening” gir et godt mentalt bilde av hva som foregår, mens ordet “ramifikasjon” neppe gir noen assosiasjoner. Jeg er usikker på hvor stor utbredelsen til “forgrening” er, men et raskt søk ga i hvert fall dette resultatet:
https://no.qaz.wiki/wiki/Ramification_(mathematics) 

**Forslag:** 
forgrene seg, forgreine seg, ramify
forgrening, forgreining, ramification
forgreningsindeks, forgreiningsindeks, ramification index

**Comment by markusvhagen** [comment]
Jeg er enig med @viktoba, og støtter heller deres forslag om å oversette ramify som å forgrene seg. Inne på liknende ord lurer jeg også på **inertia degree** og det at primtall p er **inert** i L. Jeg har ikke funnet noen gode oversettelser her. Alt dette er også inneholdt i teorien om **splitting of primes (in extensions)**, men her har jeg heller ingen gode forslag. Føler at _splitte_ er litt direkte oversatt. Har du noen forslag @viktoba?

**Comment by viktoba** [comment]
Veldig godt spørsmål! Jeg har ikke noe godt svar. 

Det jeg har hørt er at en rotkropp (= "splitting field") er den minste kroppsutvidelsen hvor et polynom splitter. Altså at prefikset "rot-" fungerer bra, men du kan liksom ikke bruke det sammen med ordene "polynom" eller "primtall". Det hadde vært flott med et annet ord enn “splitte”, men jeg vet ikke hva det skulle vært. 

NB! Da jeg søkte opp “forgrening” gikk det for fort i svingene. Den lenken jeg postet er visst til en side som bare oversetter Wikipedia-artikler med Google Translate! Jeg har med andre ord ikke noen dokumentasjon på at “forgrening” har noen utbredelse på norsk.

**Comment by petfly** [comment]
Jeg tror vi har diskutert forgrening tidligere, helt enig i at det er en god norsk oversettelse (enten den burkes eller ikke), særlig når man har støtte i tysk.

Også enig i at splitting blir litt ekkelt på norsk, er spalting et bedre alternativ? For å unngå lengre ord som bygger på "å delle opp" e.l.

**Comment by markusvhagen** [comment]
Prefikset rot fungerer bra i tilfellet polynom fordi **splitting field** av et polynom er jo nettopp kroppen som inneholder alle røttene. Det som skjer her er jo at du tar et primideal og ser hvordan det faktoriserer i heltallsringen av en større kroppsutvidelse. Jeg føler ikke prefiksen rot passer noe godt inn i dette bildet. I denne situasjonen kanskje noe med faktorisering kunne fungert bedre? Hva med noe i duren _utvidelsefaktorisering_? 

> _Q har utvidelsefaktorisering P_1^{e_1}(...)P_t^{e_t} i L_

Jeg synes egentlig det er så god klang i det ordet, men det er i alle fall veldig beskrivende for situasjonen.
