### ISSUE TITLE
Forslag til ovsersettelse av "preimage": urbilde

### ISSUE THREAD

**Issue by edvardtc** [jfremstad/matematisk_ordliste#119]
Hva tenker dere om å bruke _urbilde_ som norsk begrep for "preimage". Jeg ser at det synonyme begrepet "inverse image" har oversettelsen _invers bilde_ i ordlista, men jeg synes at det fortsatt er verdt å ha en egen oversettelse for "preimage". Man bruker på tysk [urbild](https://de.wikipedia.org/wiki/Urbild_(Mathematik)), så ordlånet vil være analogt til at man i algebra bruker _kropp_ ([körper](https://de.wikipedia.org/wiki/K%C3%B6rper_(Algebra)) på tysk).  Andre åpenbare alternativ er _inversbilde_, _forbile_, _resiprokt bilde_, _resiprokbilde_ eller _førbilde_, men jeg synes de er mindre elegante.
Er det noen som har andre forslag?

**Comment by petfly** [comment]
Jeg liker det forslaget meget godt. De andre er mer åpenbare, og har vært vurdert, men har ikke vært tilfredsstillende. Urbilde er elegant og enkel å bruke, og tysk opphav er ingen ulempe

**Comment by bervinator** [comment]
Denne termen er nå i ordlisten. 
@edvardtc: Legg gjerne til en kommentar med navn og ev. utdanningsinstitusjon, slik at vi kan legge deg til som bidragsyter.

**Comment by fredrik-bakke** [comment]
Denne ble lagt til de verifiserte termene via #126.
