### ISSUE TITLE
Riemannian geometry, Riemannian metric, connection, Levi-Civita connection, principal curvature, Gaussian curvature, Jacobi field, curvature tensor, geodesic, parallel translation, frame, frame bundle, orthogonal frame, volume, volume form, volume density, tensor bundle (differensialgeometri)

### ISSUE THREAD

**Issue by StineBerge** [jfremstad/matematisk_ordliste#12]
**Forslag:**

- [x] riemannsk geometri, riemannsk geometri, Riemannian geometry
- [x] riemannsk metrikk, riemannsk metrikk, Riemannian metric
- [x] konneksjon, konneksjon, connection
- [x] Levi-Civita konneksjonen, Levi-Civita konneksjonen, Levi-Civita connection
- [x] hovedkrumning, hovudkrumming, principal curvature
- [x] gaussisk krumning, gaussisk krumming, Gaussian curvature
- [x] jakobifelt, jacobifelt, Jacobi field
- [x] krumningstensor, krummingstensor, curvature tensor
- [x] geodetisk kurve, geodetisk kurve, geodesic
- [x] parallellforskyvning, parallellforskyving, parallel translation
- [x] ramme, ramme, frame
- [x] rammebunt, rammebunt, frame bundle
- [x] orthogonal ramme, orthogonal ramme, orthogonal frame
- [x] volum, volum, volume
- [x] volumform, volumform volume form
- [x] volumtetthet, volumtettleik, volume density
- [x] tensorbunt, tensorbunt, tensor bundle

**Merknad:**
Ordet "translation" er oversatt med parallelforskyvning i ordboken. Jeg mener dette er misvisende siden man kan forskyve ting uten at det trenger å være parallelt.

**Comment by jfremstad** [comment]
Takk for gode forslag! Jeg er enig i det meste, så har bare noen kommentarer.

*Konneksjon* høres ikke ut som et godt norsk ord i mine ører. Hva med *forbindelse*, siden en slik konstruksjon skaper en forbindelse mellom tangentrom?

Er volumtetthet forskjellig fra tetthet? Finnes det andre typer tettheter enn de som har med volum å gjøre?

* På bokmål tror jeg man må si parallellforskyv**n**ing.
* På nynorsk mener du sikkert volumtettleik, uten e?
* På engelsk skal vel *Riemannian* alltid stå med stor R.

**Comment by StineBerge** [comment]
Takk, har rettet opp i feilene. 

Får å besvare det første spørsmålet: det er ikke så bra norsk, men det er noe jeg har brukt og det man finner på store norske leksikon. For min del høres "å ta forbinnelsen av X i retning Y" helt greit ut, men har aldri hørt det brukt.

På det andre spørsmålet vil jeg si ja. På en vilkårlig mangfoldighet kan man lage en tetthetsbunt, som er en linjebunt (ligner veldig på den n-alternerende bunten, bare at du ikke krever orienterbarhet). Volumtettheten er den seksjonen av tetthetsbunten som hører til den riemannske metrikken.  (Dessuten hvis vi "density" i statestikk/analyse, og jeg vil ikke si at dirac delta funksjonen har noe med volum å gjøre).

**Comment by jfremstad** [comment]
Jeg lurer på om det kanskje er best å legge til noen merknader i disse tilfellene. Hva med

```
forbindelse,forbindelse,connection
```
med merknad om at konneksjon også er i bruk, og

```
volumtetthet, volumtettleik, volume density
```
med merknad om at termen gjelder for riemannske mangfoldigheter.

Høres det greit ut eller er det noe du vil endre/presisere?

**Comment by StineBerge** [comment]
Høres greit ut :)

**Comment by eohjelle** [comment]
Hva med å oversette _connection_ til _kobling_?

**Comment by bervinator** [comment]
Hei.
Jeg synes at kobling er en flott oversettelse, og jeg har vært i kontakt med andre som tar denne i bruk. Dette tas opp på vårt neste møte.
