### ISSUE TITLE
Solvable - opplø(y)sbar

### ISSUE THREAD

**Issue by Amund211** [jfremstad/matematisk_ordliste#123]
**Forslag:**
```
oppløsbar gruppe,oppløysbar gruppe,solvable group
```

**Merknad:**
Det er også en mulighet å kun oversette adjektivet, men da vil konteksten være mindre tydelig.
```
oppløsbar,oppløysbar,solvable
```

**Kommentar:**
Skal ikke si meg så alt for sikker på at disse termene stemmer overens, men av det jeg har forstått så gjør de det.

Ref:
https://en.wikipedia.org/wiki/Solvable_group
https://no.wikipedia.org/wiki/Gruppeteori#Oppl%C3%B8sbare_grupper

**Comment by bervinator** [comment]
Begge disse termene ligger allerede oversatt i ordlisten. Vi har riktignok valgt oversettelsen løsbar fremfor oppløsbar. 

Det har seg jo slik at galoisgruppen til et polynom _p_ er løsbar hvis og bare hvis ligningen _p(x)_ er løsbar vha. de fire regningsartene og rotutdragning. Vi fjernet forstavelsen opp- slik at løsbarhetsbegrepet for grupper samsvarer med løsbarhet for polynomligninger.

Jeg lar denne posten stå åpen litt til, i tilfelle noen skulle ha motforestillinger.

**Comment by Amund211** [comment]
Ja, det er forståelig. Jeg burde, så klart, sjekket solvable, men jeg fikk ingen resultater da jeg søkte på oppløsbar.
