### ISSUE TITLE
Superset på norsk?

### ISSUE THREAD

**Issue by rknb** [jfremstad/matematisk_ordliste#129]
Hva er det vanlig å kalle dette på norsk? Supermengde? Overmengde?

**Comment by bervinator** [comment]
Takk for spørsmål!
Her synes jeg overmengde høres helt kurant ut. Jeg kommer ikke på noen bedre forslag.

**Comment by bervinator** [comment]
Jeg sender dette videre i systemet. Posten lukkes, og gjenåpnes dersom termen (mot formodning) skulle møte motstand.

**Comment by bervinator** [comment]
Jeg er usikker på om du er oppført som [bidragsyter](https://github.com/jfremstad/matematisk_ordliste/blob/master/BIDRAGSYTERE.md). Kommenter gjerne navn og utdanningsinstitusjon/arbeidsplass dersom du at jeg fører deg opp.
