### ISSUE TITLE
exterior, exterior differentiation, exterior algebra, homogeneous space, Christoffel symbol, geodesically complete, torque, angular velocity, angular momentum, covariant derivative, manifold, sub-manifold, fiber, fibre bundle,  Ricci curvature, first integral, Klein bottle, fiber metric, mean curvature, symplectic form, symplectic geometry, symplectic vector space, Hamilton's equation, Hamiltonian mechanics, contraction, de Rham complex (differensialgeometri)

### ISSUE THREAD

**Issue by StineBerge** [jfremstad/matematisk_ordliste#13]
**Forslag:**

- [x] ytre, ytre, exterior
- [x] ytre derivering, ytre derivering, exterior differentiation
- [x] ytre algebra, ytre algebra, exterior algebra
- [x] homogent rom, homogent rom, homogeneous space
- [x] christoffelske symboler, christoffelske symbol, Christoffel symbol
- [ ] geodetisk komplett, geodetisk komplett, geodesically complete
- [ ] dreiemoment, dreiemoment, torque
- [ ] vinkelhastighet, vinkelfart, angular velocity
- [ ] drivmoment, vinkelmoment,  angular momentum
- [x] kovariant derivert, kovariant derivert, covariant derivative
- [x] mangfoldighet, mangfald, manifold
- [x] undermangfoldighet, undermangfald, sub-manifold
- [x] fiber, fiber, fiber
- [x] fiberbunt, fiberbunt, fibre bundle
- [x] riccikrumning, riccikrumming,  Ricci curvature
- [x] første integral, første integral, first integral
- [x] kleinflasken, kleinflaska, Klein bottle
- [x] fibermetrikk, fibermetrikk, fiber metric
- [x] gjennomsnittskrumning, gjennomsnittskrumming, mean curvature
- [x] symplektisk form, symplektisk form, symplectic form
- [x] symplektisk geometri, symplektisk geometri, symplectic geometry
- [x] symplektisk vektorrom, symplektisk vektorrom, symplectic vector space
- [x] hamiltons likninger, hamiltons likninger, Hamilton's equation
- [x] hamiltonmekanikk, hamiltonmekanikk, Hamiltonian mechanics
- [x] sammentrekning, samantrekning, contraction
- [ ] de Rham-kompleks, de Rham-kompleks, de Rham complex

**Merknad:**
Ordene "angular velocity" og "angular momentum" har flere oversettelser.

**Comment by johahaug** [comment]
Dette er bare en liten kommentar på mange gode forslag. Jeg har snakket med en fysiker om termene _angular velocity_ og _angular momentum_. Han er enig i at vi bør oversette _angular velocity_ til vinkelhastighet, men foreslår oppslaget 

´´´dreieimpuls/drivmoment/spinn,dreieimpuls/drivmoment/spinn, angular momentum´´´

med merknaden "Legg merke til at hvilken oversettelse som foretrekkes, er avhengig av kontekst. For eksempel bruker man i kvantemekanikk ofte oversettelsen spinn, mens man i klassisk mekanikk gjerne foretrekker dreieimpuls."

Forøvrig: Hastigheit er et godkjent nynorskord, så jeg mener det bør hete vinkelhastigheit på nynorsk.

**Comment by bervinator** [comment]
Følgende termer skal undersøkes nærmere:
geodetisk kurve, dreiemoment, vinkelhastighet, drivmoment og de Rham-kompleks.
De legges trolig til verifisering i januar.
