### ISSUE TITLE
Martingale

### ISSUE THREAD

**Issue by danielKSt** [jfremstad/matematisk_ordliste#130]
**Forslag til oversettelse**
martingal, martingal, martingale

**Kommentar**
Dette er jo eit ganske viktig begrep innan stokastiske prosessar, så hadde vore kjekt med oversettelse. Det ser ut som andre språk har nytta samme stil i oversettelse som eg foreslår over. Eg kjem ikkje på nokon meir passande begrep heller, men om nokon har eit forslag som er meir beskrivande hadde jo det vore supert.

**Comment by bervinator** [comment]
Jeg sender dette videre i system. Posten lukkes, og gjenåpnes dersom termen (mot formodning) skulle møte motstand.
