### ISSUE TITLE
Exchangeable random variables

### ISSUE THREAD

**Issue by jtufto** [jfremstad/matematisk_ordliste#132]
**Forslag:**
Bokmål: Ombyttbare stokastiske variabler
Nynorsk: Ombytelege stokastiske variablar

**Kommentar:**
Se https://en.wikipedia.org/wiki/Exchangeable_random_variables for definisjon.

**Comment by bervinator** [comment]
Jeg sender dette videre i system. Posten lukkes, og gjenåpnes dersom termen (mot formodning) skulle møte motstand.
