### ISSUE TITLE
Sletting av gamle brancher

### ISSUE THREAD

**Issue by ghost** [jfremstad/matematisk_ordliste#134]
@jfremstad @bervinator Vil dere slette gamle brancher som ikke lenger er i bruk?

**Comment by bervinator** [comment]
Takk Simon, dette er ryddet opp. Kunne én av dere godtatt oppdateringen av språklige konvensjoner?

**Comment by simonfoldvik** [comment]
@bervinator Flott! Jeg har godkjent PR-en din om språklige konvensjoner.

@jfremstad Får du slettet eller merget den inaktive branchen din også, så er vi i mål? Ser ikke ut til at den har blitt oppdatert på over to år.

**Comment by jfremstad** [comment]
Ser ut som det var en test hvor jeg dyttet datasettet i datatable. Mener å huske at den hadde bedre søking mtp. aksenter og utenlandske tegn. Hvis noen har lyst å se på nettsiden kan det være verdt å ta en titt på, hvis ikke kan jeg slette den.

**Comment by simonfoldvik** [comment]
@jfremstad Da kan vi sikkert ta vare på den litt til. Ser den er 9 commits bak `master`, så kanskje bare merge `master` inn på den branchen, så den er up-to-date?

**Comment by jfremstad** [comment]
Rebaset den på master nå
