### ISSUE TITLE
Grammatisk genus mangler

### ISSUE THREAD

**Issue by abhijatve** [jfremstad/matematisk_ordliste#139]
Eksempel: heter det "en" eller "et" topos? På nynorsk vil også hunkjønn være nødvendig å dokumentere.

**Comment by bervinator** [comment]
Jeg er enig i at det ikke er åpenbart hva grammatisk kjønn er i dette tilfellet, men det er hankjønn, både på bokmål og nynorsk [https://naob.no/ordbok/topos](NAOB). Takk for innvendingen! Det oppdateres etter neste verifiseringsrunde.

**Comment by abhijatve** [comment]
Jeg personlig lurte ikke på hva kjønnet til "topos" var - det var et eksempel. Jeg ville bare påpeke at genus bør dokumenteres i ordlisten etter norsk leksikografisk skikk :).

**Comment by bervinator** [comment]
Det setter vi stor pris på! Om du kommer over andre termer der kjønnet ikke er åpenbart, er det bare å kommentere.
