### ISSUE TITLE
Frenet frame, totally geodesic, contact geometry, contact structure, contact form, exact, Killing field, binormal unit vector, tangent space, tangent bundle, cotangent space, cotangent bundle, bundle charts, vector bundle, bracket generating, sectional curvature, isotropic, coisotropic, Minkowski space, Lie derivative, exponential map, normal coordinates, one-parameter subgroup, normal geodesic, abnormal geodesic, sub-Riemannian geometry, bracket, Lie bracket, Poisson bracket, Poisson algebra, phase space, differential form, conjugate point, antipodal point (differensialgeometri)

### ISSUE THREAD

**Issue by StineBerge** [jfremstad/matematisk_ordliste#14]
**Forslag:**

- [x] frenetramme, frenetramme, Frenet frame
- [ ] fullstendig geodetisk, fullstendig geodetisk, totally geodesic
- [x] kontaktgeometri, kontaktgeometri, contact geometry
- [x] kontaktstruktur, kontaktstruktur, contact structure
- [x] kontaktform, kontaktform, contact form
- [x] eksakt, eksakt, exact
- [x] killingfelt, killingfelt, Killing field
- [x] binormal enhetsvektor, binormal einingsvektor, binormal binormal unit vector
- [x] tangentrom, tangentrom, tangent space
- [x] kotangentrom, kotangentrom, cotangent space
- [x] tangentbunt, tangentbunt, tangent bundle
- [x] kotangentbunt, kotangentbunt, cotangent bundle
- [x] buntkart, buntkart, bundle charts
- [x] vektorbunt, vectorbunt, vector bundle
- [x] klammegenererende, klammegenererande, bracket generating
- [x] snittkrumning, snittkrumming, sectional curvature
- [x] isotropisk, isotropisk, isotropic
- [x] koisotropisk, koisotropisk, coisotropic
- [x] minkowskirom, minkowskirom, Minkowski space
- [x] liederivert, liederivert, Lie derivative
- [ ] eksponentialavbildningen, eksponentialavbildingen, exponential map
- [x] normale kordinater, normale koridinater, normal coordinates
- [x] enparameterundergruppe, einparameterundergruppe, one-parameter subgroup
- [ ] normal geodetisk kurve, normal geodetisk kurve, normal geodesic
- [ ] unormal geodetetisk kurve, unormal geodetetisk kurve, abnormal geodesic
- [x] underriemannsk geometri, underriemannsk geometri, sub-Riemannian geometry
- [x] klamme, klamme, bracket
- [x] lieklamme, lieklamme. Lie bracket
- [x] poissonklamme, poissonklamme, Poisson bracket
- [x] poissonalgebra, poissonalgebra, Poisson algebra
- [x] faserom, faserom, phase space
- [x] differensialform, differensialform, differential form
- [x] konjungatpunkt, konjungatpunkt, conjugate point
- [x] antipodalt punkt, antipodalt punkt, antipodal point

**Merknad:**
"Sectional kurvature" kunne også bli oversatt med "tversnittkrumning" for å ikke forveksle det sammen med gjennomsnittskrumningen.

**Comment by bervinator** [comment]
Mange takk for alle dine forslag! Vi setter meget stor pris på dem. De vil gå gjennom verifikasjonsprosessen.

mvh. Erlend Due Børve

**Comment by bervinator** [comment]
Her er det aller meste verifisert. Det skal undersøkes nærmere hvordan termer om geodetiske kurver og eksponesialavbildninger burde føres opp.
