### ISSUE TITLE
Noen korreksjoner

### ISSUE THREAD

**Issue by fredrik-bakke** [jfremstad/matematisk_ordliste#144]
Hei igjen!
Her fører jeg opp noen foreslåtte endringer/spørsmål til ordboka

- "optimalisering" og "optimaliseringsproblem" står oppført 2 ganger, én gang med kommentar.
- "applied mathematics" står oppført 2 ganger.
- Bør ikke "skeletal" være en annen norsk oversettelse av det engelske ordet "skeletal"?
- Bør ikke "sil" være en annen oversettelse for "sieve" på lik linje med "såld"?

**Comment by bervinator** [comment]
Veldig godt fanget opp! De to første er åpenbare slurvefeil, og er rettet opp. Det kan ta et par dager før nettsiden er oppdatert. 
De to siste tror jeg forblir uendret i første omgang. Vi har veid opp skeletal skjelett og skjelettal, og såld virker mer etablerert enn sil.

**Comment by fredrik-bakke** [comment]
Alright, tusen takk for responsen! 👍
