### ISSUE TITLE
Forutsetninger

### ISSUE THREAD

**Issue by ellinorlekven** [jfremstad/matematisk_ordliste#148]
Fant ikke ordet forutsetninger i ordlisten deres

**Comment by bervinator** [comment]
Akkurat dette ordet skal det være mulig å finne i en vanlig ordbok. Noen hverdagslige ord er tatt med i vår ordliste, men dette gjelder ord som enten er veldig hyppig brukt av matematikere eller oversettes annerledes i en matematisk sammenheng. 

Ordet forutsetning kan ha flere oversettelser på engelsk, for eksempel «prerequisite» eller «assumption». Er det sistnevnte oversettelse du sikter til?

**Comment by fredrik-bakke** [comment]
Jeg lukker denne saken da det mangler informasjon for å gjøre noe med den.
