### ISSUE TITLE
Automatisert korreksjon og publisering

### ISSUE THREAD

**Issue by fredrik-bakke** [jfremstad/matematisk_ordliste#150]
Hei!
Jeg ser dette prosjektet utnytter en automatisert arbeidsflyt for å kvalitetssikre [verifiserte_termer.csv](https://github.com/jfremstad/matematisk_ordliste/blob/master/verifiserte_termer.csv), men visste dere at det er mulig å automatisk korrigere disse feilene også? Se eksempelvis [her](https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests/).

En annen ting jeg tenkte jeg kunne nevne er at det også er mulig å sette opp en automatisert arbeidsflyt for publisering av nettsiden fra mestergrenen.

Jeg har litt erfaring med automatiserte arbeidsflyter og stiller meg gjerne til rådighet hvis det ønskes hjelp med dette.

**Comment by jfremstad** [comment]
Hei!

Automatisk korrigering er en fin idé, men jeg heller mot å gjøre det i dette prosjektet. Med mindre korrigeringsverktøyet er perfekt fører det ofte til mer trøbbel enn det er verdt. Forbedring av kvalitetssikringsskriptene er flott da! :smile: 

Vi har automatisk publisering av nettsiden mot https://matematikkradet.no/ordliste/ vha. webhooks, men flott du kommer med gode idéer :grin:

**Comment by fredrik-bakke** [comment]
Takk for responsen!

Jeg har forståelse for stillingen din, men tanken min var i første omgang at hoppet til å få datamaskinen til å fikse feilene istedet for å bare skrike til bidragsyterene og fortelle de hvordan de skal fikse feilene sine selv ikke bør være så stor (på de enkle feilene som allerede oppdages og "korrigeres" av den). Som en utvidelse av denne idéen kunne man da automatisert andre ting også, som å alfabetisere ordlista.

Igjen så insisterer jeg på ingen måte at disse endringene skal implementeres, jeg ønsket bare å lufte tanken.
