### ISSUE TITLE
Forslag til nye termer (algebra)

### ISSUE THREAD

**Issue by johahaug** [jfremstad/matematisk_ordliste#152]
Her er noen forslag til termer som foreløpig ikke er med i ordlista:

auslanderalgebra,auslanderalgebra,Auslander algebra
Auslander-Reiten-triangel,Auslander-Reiten-triangel,Auslander–Reiten triangle
utvidelseskategori,utvidingskategori,category of extensions
konflasjon,konflasjon,conflation
deflasjon,deflasjon,deflation
frobeniusalgebra,frobeniusalgebra,Frobenius algebra
frobeniuskategori,frobeniuskategori,Frobenius category
funktorielt endelig,funktorielt endeleg,functorially finite
kovariant endelig,kovariant endeleg,covariantly finite
kontravariant endelig,kontravariant endeleg,contravariantly finite
homologisk algebra,homologisk algebra,homological algebra
høyere homologisk algebra,høgare homologisk algebra,higher homological algebra
mild algebra,mild algebra,gentle algebra
inflasjon,inflasjon,inflation
koszuldual,koszuldual,Koszul dual
serrefunktor,serrefunktor,Serre functor
vippemodul,vippemodul,tilting module
vippeobjekt,vippeobjekt,tilting object
preprojektiv,preprojektiv,preprojective
preinjektiv,preinjektiv,preinjective
preprojektiv algebra,preprojektiv algebra,preprojective algebra

**Comment by fredrik-bakke** [comment]
Disse ble med i ordlisten via #160, så da lukker jeg tråden :)
