### ISSUE TITLE
(Set) difference

### ISSUE THREAD

**Issue by MortGron** [jfremstad/matematisk_ordliste#163]
**Forslag til oversettelse**
* mengdedifferanse, mengddifferanse, set difference

**Kommentar**
Hvis det er klart ut fra sammenhengen vil vel man ofte skrive "difference" på engelsk og "differanse" på norsk uten å spesifisere "set" eller "mengde/mengd"

**Comment by fredrik-bakke** [comment]
Hei Morten og tusen takk for bidraget! Dette vil bli tatt med i neste verifiseringsrunde. Beklager sen respons, desverre har denne gått under radaren min.
