### ISSUE TITLE
Concealed and tilted algebras

### ISSUE THREAD

**Issue by jagr2808** [jfremstad/matematisk_ordliste#169]
**Forslag:**
tilslørt algebra,tilsløra algebra,concealed algebra
vippet algebra,vippa algebra,tilted algebra
kvasivippet algebra,kvasivippa algebra,quasi-tilted algebra

**Comment by fredrik-bakke** [comment]
Tusen takk for forslagene! Disse vil bli tatt opp i neste verifiseringsrunde. Dersom du ønsker å bli oppført som bidragsyter, gjerne kommenter fullt navn og eventuell utdanningsinstitusjonstilknytning eller arbeidsgiver under.

**Comment by fredrik-bakke** [comment]
Hei igjen. Dette er helt utenfor mitt kunnskapsområde, men har du vurdert oversettelsen "skjult algebra" for "concealed algebra"? Hva er grunnlaget for å foretrekke "tilslørt"?

**Comment by jagr2808** [comment]
Hei, 
Bakgrunnen er at jeg og to kollegaer nylig hadde et prosjekt om tilslørte algebraer, og derav trengte et norskt ord å bruke med hverandre. Vi smakte på både "gjemt" og "skjult", men ble mest fornøyd med tilslørt.

Tilslørte algebraer er veldig nære å være hereditære, og er således nesten en hereditær algebra i forkledning. Altså, en tilslørt algebra.

Såvidt jeg har forstått er det dette som er etymologien av det engelske uttrykket, men det har jeg ingen sikre kilder på.

"Skjult" kunne nok også vært et passende begrep, men det høres jo litt mindre fancy ut.

**Comment by fredrik-bakke** [comment]
Hei igjen @jagr2808. Under verifiseringsprosessen ble den alternative oversettelsen "vippealgebra" foreslått for "tilted algebra". Er dette en oversettelse du/dere har vurdert?

**Comment by jagr2808** [comment]
Sånn jeg tenker på begrepet er bat du starter med en hereditær algebra, deretter vipper den og får en vippet algebra. Vippealgebra vil nok også fungere, uten at jeg har vurdert det veldig nøye. Vippa algebraer er også en del vanligere enn de to andre forslagene, så kanskje verdt å gå runden i 8. etasje å se hvor etablert begrepet er fra før av.

Dette er Jacob Grevstad foresten, hei.

**Comment by jagr2808** [comment]
Delte meninger i etasjen. Kan hende det er en ide å skrive opp begge...

**Comment by fredrik-bakke** [comment]
Hei igjen, Erlend later til å være enig med ditt opprinnelige forslag og veide inn med følgende: 

> Jeg foretrekker (kvasi)vippet algebra over (kvasi)vippealgebra. Termen vippemodul er allerede i ordlisten, og vippede algebraer er endomorfialgebraer til vippemoduler. Med andre ord er det vippemodulen som muliggjør vipping, og den vippede algebraen er resultatet av vippingen. Dermed blir (kvasi)vippet algebra over (kvasi)vippealgebra konsistent med våre (uskrevne) konvensjoner. 

Så da foreslår jeg at vi går med dette.
