### ISSUE TITLE
Kvadratisk gjensidighet?

### ISSUE THREAD

**Issue by PetterABergh** [jfremstad/matematisk_ordliste#170]
Hei,

Jeg foreleser i tallteori på NTNU denne høsten. Jeg ser at termen «kvadratisk resiprositet» er oppført som oversettelse av det engelske «quadratic reciprocity,» et uttrykk som er mye brukt i tallteori. Burde også «kvadratisk gjensidighet» kanskje oppføres som synonym?

Hilsen Petter

**Comment by fredrik-bakke** [comment]
Tusen takk for forslaget, Petter. Det vil bli tatt opp i neste verifiseringsrunde.
