### ISSUE TITLE
Likelihood function (statistikk)

### ISSUE THREAD

**Issue by mldnorheim** [jfremstad/matematisk_ordliste#2]
**Kommentar**
Det var noe i statistikk som het "likelihood (function)", som jeg ikke fant i lista her. Jeg husker at man ikke kunne oversette "likelihood" til "sannsynlighet" fordi det allerede var oversettelsen av "probability" (som ikke brukes om samme funksjon), men det er lenge siden jeg tok statistikk-fag og jeg finner ikke ut hva den norske oversettelsen var. Hjelp?

**Comment by hanche** [comment]
Dette er ikke mitt felt, men jeg mener å ha hørt «rimelighet» brukt om dette begrepet. Dette må selvsagt sjekkes med noen som vet.

**Comment by mldnorheim** [comment]
Ja, det høres kjent ut! Veldig mulig at det var "rimelighet" vi kalte det :)

**Comment by johahaug** [comment]
[Denne](www.uio.no/studier/emner/matnat/math/nedlagte-emner/STK4010/h11/OrdlisteSTK4010.pdf) ordlista fra UiO ser ut til å støtte oversettelsen rimelighetsfunksjon. Jeg skal få dette bekreftet fra noen fra statistikkfeltet slik at vi er helt sikre.

**Comment by johahaug** [comment]
Jeg har fått bekreftet at denne oversettelsen brukes av seriøse kilder (f.eks. Høyland). Termen kommer med i neste verifiseringsrunde, og jeg lukker derfor denne tråden.

**Comment by johahaug** [comment]
Forresten, vi får jo et problem med nynorskformen her. Har du noe forslag til hva rimelighetsfunksjon burde hete på nynorsk, @OleVaage?

**Comment by OleVaage** [comment]
"rimelegheitsfunksjon" er helt gangbart på nynorsk.
