### ISSUE TITLE
Tegnsetting for synonyme uttrykk

### ISSUE THREAD

**Issue by johahaug** [jfremstad/matematisk_ordliste#24]
Vi fører opp synonymer med tegnet "/" mellom. 

Bør man når man skal skille mellom synonyme uttrykk som består av flere ord (f.eks. _analysis of variance/variance analysis_) ha mellomrom til høyre og venstre for "/" (altså _analysis of variance / variance analysis_)? Vi har fått tilbakemelding om at dette er vanlig praksis blant noen korrekturlesere for matematiske læreverk. 

Har Språkrådet noen formening om eller retningslinjer for dette, @OleVaage?

**Comment by bervinator** [comment]
Gjelder det samme om det er ett ord på den ene siden av parentesen, men flere på den andre. 
Et verifisert eksempel er _avvikende observasjon/utligger_.

**Comment by OleVaage** [comment]
I løpende tekst er det vanlig å skille med mellomrom før og etter skråstreken når et eller begge begrepene består av flerordsuttrykk. Som jeg var inne på tidlig i prosjektet, er konvensjon i termbaser å etablere et eget felt for synonymer, slik at man ikke trenger skråstrek. Når skråstrek nå benyttes for å skille synonymer i samme felt, kan man følge konvensjonen fra løpende tekst som en fast regel i prosjektet. Men: Jeg vil imidlertid mene at det ikke er påkrevd på samme måte som løpende tekst. Der har det en spesifikk funksjon: Hjelpe leseren å skille mellom begrepene på hver side av skråstreken og resten av setningen. Er det mellomrom, vet leseren at et eller begge av begrepene består av flere ord.

**Comment by johahaug** [comment]
Takk for svar. For å unngå forvirring (f.eks. at noen kunne tenkes å tro at avvikende i eksempelet til Erlend ovenfor skal distribueres på både observasjon og utligger) velger vi å bruke mellomrom før og etter / i tilfeller der det er snakk om uttrykk som består av flere ord. 

Jeg legger dette inn i konvensjonene, og @jfremstad går gjennom termbasen og sørger for at dette gjøres gjennomgående.
