### ISSUE TITLE
Homothety, homothetic vector field osv.

### ISSUE THREAD

**Issue by johahaug** [jfremstad/matematisk_ordliste#3]
**Forslag til oversettelse**
* homoteti,homoteti,homothety
* homotetisk vektorfelt,homotetisk vektorfelt,homothetic vector field

**Kommentar**
Sigbjørn Hervik, som blant annet er fagansvarlig for en del matematiske emner på snl.no, har stilt oss spørsmål om hvordan vi vil oversette engelske homothety og homothetic vector field. Jeg synes egentlig ikke de to forslagene som er nevnt ovenfor er spesielt gode, og håper vi kan komme fram til noe bedre. Noen som har innspill på dette?

**Comment by bervinator** [comment]
Adjektivet homotetisk brukes av SNL [her](https://snl.no/homotetisk).
Jeg finner hyppig bruk av termen homotetisk avbildning på Nasjonalbibliotekets sider, spesielt i gamle geometribøker for gymnaset. 
Det er også treff på homoteti, i (omtrent) samme betydning. 
Det er ingen treff på homotet.

Jeg tror det kan være greit å skille mellom konseptet og begrepet.
Frasen "homoteti i planet" burde være grei nok, selv om man skulle ende opp å kalle det en homotetisk avbildning. Da svarer homoteti til en homotetisk avbildning slik som integrasjon (selve kunsten) svarer til den integrerte av en funksjon.

Jeg foreslår (men er villig til å la meg overbevise om noe annet) å endre homoteti til homotetisk avbildning og la homotetisk vektorfelt stå slik det står. Evt. kan vi legge til 
homoteti,homoteti,homothety,
med en merknad om det er snakk om konseptet og ikke en homotetisk avbildning.

**Comment by johahaug** [comment]
Godt poeng med snl-artikkelen, og også at oversettelsene allerede er en del brukt andre steder. 

Hvis vi synes oversettelsen homotetisk er grei, som jeg tenker vi kan - i lys av kildene du nevner, ser jeg ikke heller noe problem med å oversette til homoteti. Språklig sett er det jo ingen stor forskjell her. Siden man også godt kan snakke om _homothetic map_, ville jeg foretrekke om vi ikke brukte oversettelsen homotetisk avbildning for _homothety_.

Jeg foreslår at vi fører opp følgende oversettelser:

```
homoteti,homoteti,homothety,
homotetisk vektorfelt,homotetisk vektorfelt,homothetic vector field,
homotetisk,homotetisk,homothetic,
```

Jeg tenker at det ikke er nødvendig med merknader her.

**Comment by bervinator** [comment]
Jeg stiller meg bak forslagene, og er enig i at merknader ikke trengs.

**Comment by johahaug** [comment]
Da legger jeg dette inn som forslag til neste verifiseringsrunde og lukker denne tråden.
