### ISSUE TITLE
Subordinate (as in partition of unity subordinate to a given covering)

### ISSUE THREAD

**Issue by htnguyent** [jfremstad/matematisk_ordliste#31]

**Comment by bervinator** [comment]
I andre sammenhenger oversettes _subordinate_ til underordnet, som kanskje passer også her. Vi kan ta spørsmålet ditt videre til fagpersoner.

**Comment by johahaug** [comment]
Dette oversettes i boka [topologi](https://www.nb.no/items/a67ffeadbdcb1a25cc699e46f1836c26?page=0&searchText=underordnet) av Per Holm og Jon Reed til underordnet. Man sier at en partisjon er underordnet en overdekning. Jeg foreslår derfor at vi fører opp termen

underordnet,underordnet,subordinate,.

**Comment by johahaug** [comment]
Jeg legger inn forslaget ovenfor til det som skal kontrolleres i neste verifiseringsrunde og lukker denne tråden.
