### ISSUE TITLE
Et par nynorsk spørsmål

### ISSUE THREAD

**Issue by bervinator** [jfremstad/matematisk_ordliste#32]
På nynorsk er det både lovlig med både første og fyrste. Vi ønsker å konsekvent holde oss til én av dem. Hvilken kan du anbefale, @OleVaage?

Vi har også et tilsvarende spørsmål om jamvekt/likevekt. Hvilken av disse blir mest naturlig å velge mhp. midtlinjeprinsippet?

**Comment by OleVaage** [comment]
Jeg har sett i tidligere termprosjekt som praktiserer midtlinjeprinsippet (termbasen Snorre fra Standard Norge), og der har vi benyttet oss av "først" og "jamvekt".

**Comment by bervinator** [comment]
Mange takk!
