### ISSUE TITLE
Genus til forkortelser fra engelsk (en, ei eller et PID?)

### ISSUE THREAD

**Issue by viktoba** [jfremstad/matematisk_ordliste#38]
Engelske forkortelser som PID, UFD, ODE og PDE er oppført i ordboka, men uten grammatisk kjønn. Det er selvfølgelig en veldig liten detalj, men jeg tror det kan være til hjelp å ha et oppført kjønn når man skal ta disse ordene i bruk. Lar det seg gjøre å bestemme en norm for dette?

En idé er å la kjønnet til ordet som forkortes være avgjørende, dvs. at det skal hete "et PID", fordi det heter "et hovedidealområde". Men da får man i bestemt form "PID-et" , som kanskje kan være litt krøkkete å uttale?

Uansett hvilke genus man går får, så tror jeg man med fordel kunne hatt en merknad om genus til disse termene.

**Comment by johahaug** [comment]
Godt innspill. Jeg har ikke tenkt på dette, men innser at jeg selv pleier å bruke hankjønn for alle de nevnte eksemplene, selv om dette bryter med den kanskje mest logiske "regelen" som du skisserer.

Har dere i Språkrådet noen tanker om hvordan dette generelt bør gjøres, @OleVaage?

**Comment by OleVaage** [comment]
En vanlig tilnærming for genustilordninger til forkortelser er å ta utgangspunkt i den semantiske kjernen, dvs. det siste leddet i fullformen. Betyr D-en i PID "domain", dvs. domene, eller kanskje område. Både domene og område er intetkjønn, så det taler for "et PID". Når jeg søker på nettet på "en PDI", gir det treff på "en PID-regulator". Her er jo regulator hankjønn, derav hankjønnsartikkelen. 

Merk at dette er en annen tilnærmingsmåte enn låneord fra engelsk, som ofte får hankjønn.

**Comment by OleVaage** [comment]
Tja, selv om man bruker engelsk forkortelse, kan man få genustilordning basert på den norske semantiske kjernen, jf. et ISBN, der N står for (et) nummer. 
Her er det snakk om tilnærmingsmåter, ikke regler. En annen tilnærmingsmåte er å se på faktisk bruk av genus for hvert enkelt tilfelle. Jeg fant noen tilfeller av "en PID" i bøker om Linux i nb.no, men jeg vet ikke om det er det samme begrepet. Kanskje dere finner konkrete brukseksempler på enten "et PID" eller "en PID" i nb.no? NB! Sjekk innholdet i hver bok som gir treff, for det er en del støy. En tredje tilnærmingsmåte er å se på PID som en leksikalisert forkortelse, dvs. at det har blitt et eget ord slik som f.eks. dna. Det taler for hankjønn, og kan kanskje forklare hvorfor det faller deg naturlig å bruk en slik genustilordning. 

Jeg synes at det er bra at dere tar med genus i oppføringen av slike forkortelser!

**Comment by johahaug** [comment]
Verken "en PID" eller "et PID" gir (relevante) treff i nb.no. Den eneste gode kilden jeg har funnet (se [ovenfor](https://www.uio.no/studier/emner/matnat/math/MAT4250/h13/forkunnskap.pdf)), skriver "et PID" og "et UFD". 

Et forslag til konvensjon kan være at vi som hovedregel lar kjønnet til ordet som skal forkortes være avgjørende, og kun avviker fra dette i tilfeller der det er gode kilder eller andre argumenter for å gjøre noe annet. For forkortelsene som er nevnt i denne tråden ville dette innebære at vi skriver "et PID", "et UFD", "en OED" og "en PDE".

**Comment by jfremstad** [comment]
Det høres ut som en fornuftig konvensjon. Det vil også stemme overens med hvordan PID blir brukt i Linux, der PID betyr "en prosessidentifikator". Dermed gir det mening å bruke `en PID` i operativsystemsammenheng og `et PID` i matematikken.

**Comment by johahaug** [comment]
Vi har lagt til dette som konvensjon, og vil oppdatere lista slik at dette følges. Kommenterer du fullt navn og eventuell utdanningsinstitusjon, @viktoba, så legger jeg deg til i lista over bidragsytere?

**Comment by viktoba** [comment]
Oi, stas!
Viktor Balch Barth heter jeg. 
Er student ved NTNU.
