### ISSUE TITLE
Independent Component Analysis

### ISSUE THREAD

**Issue by bowre** [jfremstad/matematisk_ordliste#40]

**Comment by bowre** [comment]
Er det kanskje så enkelt som uavhengig komponentanalyse? Man kunne også oversatt Principal Component Analysis når man er i gang.

**Comment by jfremstad** [comment]
Uavhengig komponentanalyse er det første som slår meg også. I tråd med det som har blitt oversatt tidligere, så vil *Principal component analysis* kunne oversettes til enten hovedkomponentanalyse eller prinsipalkomponentanalyse. Her tror jeg det første høres best ut, men jeg kjenner ikke til detaljene rundt begrepet.

**Comment by bowre** [comment]
Jeg er ingen ekspert på dette selv, men har lest litt om ICA i en ganske lettforståelig artikkel
av Hyvärinen og Oja: Independent Component Analysis: algorithms and applications.
På side 414 (etter ligning (5)) står det en definisjon av ICA. Det handler om å reprodusere statistisk uavhengige tidsserier (kalt komponenter) fra et sett med ulike lineære blandinger av disse. Om det blir feil å ta bort "komponent" fra uttrykket tør jeg ikke si.

[1-s2.0-S0893608000000265-main.pdf](https://github.com/jfremstad/matematisk_ordliste/files/2727310/1-s2.0-S0893608000000265-main.pdf)

**Comment by johahaug** [comment]
Den er god, og takk for kilde.

**Comment by bervinator** [comment]
Termene uavhengighetsanalyse og hovedkomponentanalyse videresendes til prosjektgruppen. Tråden lukkes, og åpnes igjen dersom noen skulle protestere.
Mange takk for forslag!
