### ISSUE TITLE
Pointed topological space, pointed manifold etc. 

### ISSUE THREAD

**Issue by johahaug** [jfremstad/matematisk_ordliste#41]
Er det noen som har noe forslag til hva dette burde oversettes til?

**Comment by bervinator** [comment]
Her synes jeg at vi burde unngå "punktert". Utrykket punktert omegn er i utstrakt bruk, og dukker opp i pensumbeskrivelser for analysekurs ([her](https://folk.uib.no/st00895/MAT111-H17/pensum-2017.pdf) og [her](https://uit.no/utdanning/emner/emne/565906/mat-2100)).

Jeg vil foreslå "topologisk rom med basispunkt" og "mangfoldighet med basispunkt". Utrykket basispunkt er brukt [her](https://www.nb.no/items/a67ffeadbdcb1a25cc699e46f1836c26?page=0&searchText=topologisk%20rom%20med%20basispunkt) (s. 134) og [her](https://folk.uio.no/rognes/papers/vnr.pdf) (som ser ut til å være manuskriptet til [denne](https://www.nb.no/items/b0a817a0c4b78f7f5f8cc54b3bd67990?page=0&searchText=basispunkt)). 

På engelsk kan dette også omtales som ett "based (topological) space" (som ikke må forveksles med "base space") eller et "(topological) space with basepoint". 

Vil også forelslå at vi oversetter den mer generelle termen "topological pair" til "topologisk par".

**Comment by johahaug** [comment]
Jeg synes "topologisk rom med basispunkt" og "mangfoldighet med basispunkt" høres bra ut, og legger disse inn som forslag til neste verifiseringsrunde. 

Angående "punktert": I tilfeller der det faktisk er et punkt som "er fjernet" fra mengden, noe som ser ut til å være tilfellet i kildene ovenfor, er vel punktert en ganske god oversettelse? Jeg er likevel enig i at oversettelsen "punktert" må unngås i tilfeller der det er snakk om å skille ut ett spesielt punkt i mengden, men ikke fjerne det.

**Comment by bervinator** [comment]
Punktert fungerer veldig bra når punktet fjernes, ja. Kunne du ha lagt til
punktert omegn også, og kanskje andre liknende termer?

**Comment by bervinator** [comment]
Tror dette kalles et "deleted neighbourhood" på engelsk.

**Comment by johahaug** [comment]
Ja, det kan jeg gjøre. Jeg lukker dermed denne tråden.

**Comment by bervinator** [comment]
"Punctured neighbourhood" er et alternativ, om ikke bedre.

**Comment by sorengam** [comment]
Blant masterstudenter på UiO har ordet "punktet" blitt brukt i begreper som "pointed topological space", som vi oversatte til "punktet topologisk rom". Det ser kanskje ut som det lett kan forveksles med "punktert", men trykket er plassert forskjellig.

**Comment by johahaug** [comment]
Jeg stiller meg umiddelbart positiv til "punktet". Kanskje vi skal legge inn dette som synonym til oversettelsene som nå er ført opp?

**Comment by bervinator** [comment]
Termene
- punktet topologisk rom
- punktet mangfoldighet
- punktet kategori
videresendes til prosjektgruppen. Jeg tviler på at dette vil møte mye motstand. Tråden lukkes.
