### ISSUE TITLE
Splitting field

### ISSUE THREAD

**Issue by johahaug** [jfremstad/matematisk_ordliste#44]
Jeg har blitt tipset om at vi mangler en oversettelse av engelske _splitting field_, som er en term som dukker opp f.eks. i galoisteori.

**Comment by bervinator** [comment]
Her blir vel rotkropp best?

**Comment by johahaug** [comment]
Rotkropp heter det, ja! Jeg tar med oversettelsen i neste verifiseringsrunde og lukker denne tråden.
