### ISSUE TITLE
Embedded pairs / Innbygde par

### ISSUE THREAD

**Issue by bowre** [jfremstad/matematisk_ordliste#45]
**Forslag:**
Innbygd par, Innbygd par, Embedded pair

**Merknad:**
Dette er fra numerisk løsning av differensialligninger. Trengte dette selv til timen i dag og sjekket om det fantes. Det er såvidt meg bekjent ingen etablert terminologi på norsk for dette, så mitt forslag _Innbygd par_ er  kun et eget påfunn.

**Kommentar:**
Da jeg søkte embedded pair i databasen fant jeg at ordet "Embedding" var oversatt til "Imbedding" både på bokmål og nynorsk. Dette synes jeg var merkelig, men kanskje en egen tråd for dette er påkrevet.

**Comment by johahaug** [comment]
Jeg synes dette virker som et godt forslag. Jeg har også opprettet diskusjonstråden #58, der bakgrunnen for den nåværende oppføringen av imbedding skisseres. 

Kjenner du noen i Oslo som det ville være naturlig å lufte dette forslaget med, @Qeeku? Ellers foreslår jeg at vi legger det inn i neste verifiseringsrunde.

**Comment by bervinator** [comment]
Denne avhenger av @58.

**Comment by bervinator** [comment]
I lys av diskusjonen i @58 foreslår jeg innebygd par (innbygd par på nynorsk) på neste verifiseringsmøte.

**Comment by bowre** [comment]
Jeg har faktisk brukt “innbygd par” en periode nå, og kommer nok til å fortsette med deg.
Kanskje jeg kan få stjerne i boka fra mållaget for å bruke nynorsk! 😀
Men fra spø til alvor, er ikke “innbygd” det rette ordet her? For meg har innebygd en litt annen betydning.

Mvh. Brynjulf

On 22 Mar 2021, at 18:37, bervinator ***@***.******@***.***>> wrote:


I lys av diskusjonen i @58<https://github.com/58> foreslår jeg innebygd par (innbygd par på nynorsk) på neste verifiseringsmøte.

**Comment by bervinator** [comment]
Om vi følger NAOB havner [innebygd](https://naob.no/ordbok/innebygd) noe nærmere meningen enn [innbygd](https://naob.no/ordbok/innbygd). Språkrådet [tillater riktignok begge](https://ordbok.uib.no/perl/ordbok.cgi?OPP=innbygd&ant_bokmaal=5&ant_nynorsk=5&begge=+&ordbok=begge), på begge målformer. 

Jeg tror det er greit å velge én av dem, men å spesifisere at dette er en valgt konvensjon. Da blir alle fornøyde, ikke minst Noregs Mållag.

Dette diskuteres med resten av termsamlerene på neste møte. Uansett hva vi bestemmer oss for, blir resonnementet vårt delt i denne tråden.

**Comment by bowre** [comment]
Ja, når jeg googler litt så kan det faktisk se ut som du har rett og jeg tar feil.
Men flott at det er valgfritt da. 😀

Brynjulf

On 22 Mar 2021, at 19:05, bervinator ***@***.******@***.***>> wrote:



Om vi følger NAOB havner innebygd<https://naob.no/ordbok/innebygd> noe nærmere meningen enn innbygd<https://naob.no/ordbok/innbygd>. Språkrådet tillater riktignok begge<https://ordbok.uib.no/perl/ordbok.cgi?OPP=innbygd&ant_bokmaal=5&ant_nynorsk=5&begge=+&ordbok=begge>, på begge målformer.

Jeg tror det er greit å velge én av dem, men å spesifisere at dette er en valgt konvensjon. Da blir alle fornøyde, ikke minst Noregs Mållag.

Dette diskuteres med resten av termsamlerene på neste møte. Uansett hva vi bestemmer oss for, blir resonnementet vårt delt i denne tråden.
