### ISSUE TITLE
Hvilken lisens har ordlista?

### ISSUE THREAD

**Issue by haraldgroven** [jfremstad/matematisk_ordliste#47]
Kunne lista vært lisensert med CC-BY-lisens for å sikre viderebruk?
https://creativecommons.org/licenses/by/4.0/deed.no
Dette vi være nyttig for å ha en kopi av lista på Wikipedia, slik at en kan sikre systematisk lenking og konsekvent terminologibruk på tvers av flere mange hundre leksikonartikler.

**Comment by jfremstad** [comment]
Vi har brukt CC-BY-SA-lisensen som du kan finne [her](https://github.com/jfremstad/matematisk_ordliste/blob/master/LICENSE).

**Comment by haraldgroven** [comment]
Flott!
Hva med å merke bunnteksten på matematikkradet.no/ordliste med 
https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-sa.png ?

**Comment by jfremstad** [comment]
Godt forslag! Jeg skal se på dette.
