### ISSUE TITLE
Symmetry, Hamiltonian, Lagrangian, action

### ISSUE THREAD

**Issue by hmarthinsen** [jfremstad/matematisk_ordliste#48]
Noen forslag fra klassisk mekanikk:

**Forslag:**
- [x] symmetri,symmetri,symmetry
- [x] hamiltonfunksjon,hamiltonfunksjon,Hamiltonian
- [x] lagrangefunksjon,lagrangefunksjon,Lagrangian
- [x] virkning,verknad,action

**Merknad:**
Hamiltonian og Lagrangian brukes også som adjektiv, men her er de substantiv.

**Comment by Qeeku** [comment]
Takk for gode forslag! Vi legger til symmetri og virkning, slik du har ført dem opp, i neste pulje.

Angående _Hamiltonian_: jeg diskuterte denne termen med en matematikkprofessor ved UiO som jobber med partielle differensiallikninger, og vedkommende mener at det er naturlig å skille mellom begrepene hamiltonfunksjon og hamiltonoperator, selv om begge oversettes til _Hamiltonian_ på engelsk. Vi kom da frem til at det vil være best å føre opp to termer:

`hamiltonfunksjon,hamiltonfunksjon,Hamiltonian,`,
`hamiltonoperator,hamiltonoperator,Hamiltonian,`.

Når det kommer til _Lagrangian_, ser lagrangefunksjon ut som en god oversettelse, slik du har foreslått. Man snakker også om _Lagrangians_, _null Lagrangians_ og så videre i variasjonsanalyse. Her må jeg undersøke litt mer før termen blir lagt til, men den legges sannsynligvis til slik du har oppført den.

Si gjerne ifra om du har noen innvendinger til dette.

**Comment by bervinator** [comment]
Disse termene er på vei inn i ordlisten. Mange takk for innspill!
