### ISSUE TITLE
iterat (substantiv)

### ISSUE THREAD

**Issue by hmarthinsen** [jfremstad/matematisk_ordliste#49]
**Forslag til oversettelse**
* iterat,iterat,iterate

**Kommentar**
Jeg har hørt ordet "iterat" bli brukt om x i iterasjonen x -> f(x). Er dette vanlig? Kan man bruke "an iterate"/"et iterat" om dette?

**Comment by johahaug** [comment]
Jeg har ikke hørt denne bruken, og må innrømme jeg synes det umiddelbart høres litt fremmed ut. Samtidig gir både iterasjon (som er lagt til ordlisten) og iterere treff i [Språkrådets ordliste](https://ordbok.uib.no/perl/ordbok.cgi?OPP=iterere&ant_bokmaal=5&ant_nynorsk=5&begge=+&ordbok=begge), og dette ville jo eventuelt bli en beslektet oversettelse.

**Comment by bervinator** [comment]
Denne termen har blitt diskutert og er nå på vei inn i ordlisten.
Mange takk for innspill!
