### ISSUE TITLE
vektorflyt

### ISSUE THREAD

**Issue by hmarthinsen** [jfremstad/matematisk_ordliste#50]
**Forslag:**
vektorflyt,vektorflyt,vector flow

**Kommentar:**
Flyten generert av et vektorfelt burde kalles for "vektorflyt" på norsk. På engelsk er begrepet "vector flow" allerede innarbeidet.

**Comment by johahaug** [comment]
Dette virker som et godt forslag. Jeg tror jeg har hørt en foreleser ved NTNU bruke denne oversettelsen.

**Comment by johahaug** [comment]
Dette er lagt inn blant en samling oversettelser som skal gjennom en verifiseringsrunde, og deretter vil dukke opp på den offentlige ordlista. Denne tråden kan dermed lukkes.
