### ISSUE TITLE
definisjonsmengde, verdimengde, verdiområde

### ISSUE THREAD

**Issue by hmarthinsen** [jfremstad/matematisk_ordliste#51]
**Forslag:**
definisjonsmengde,definisjonsmengd,domain
verdimengde,verdimengd,image
verdiområde,verdiområde,codomain

**Merknad:**
På engelsk brukes "range" både for verdimengde og verdiområde, noe som kan skape forvirring.

**Comment by johahaug** [comment]
Takk for flere gode innspill, @hmarthinsen! Legg gjerne igjen fullt navn og eventuell tilhørighet til universitet/institusjon, så blir du lagt til i lista over bidragsytere. 

Enig i å legge til verdiområde som foreslått.

For _domain_ foreslår jeg
```
definisjonsmengde/definisjonsområde,definisjonsmengd/definisjonsområde,domain,"Oversettelsen gjelder blant annet når det er snakk om funksjoner og utelukker ikke at termen kan benyttes ulikt i andre sammenhenger."
```

Bakgrunnen for merknaden er innspill om at _domain_ også kan oversettes til _sammenhengende omegn_ i f.eks. kompleks analyse, og at oversettelsen dermed er avhengig av kontekst. 

Ang. _image_: Her må vi ta en grundigere gjennomgang. Vi har oversettelsen bilde liggende ute, og her bør det nok legges til en merknad. I tillegg bør verdimengde inn (noen bruker også bildemengde - eller biletmengd på nynorsk), og vi må formulere en merknad som gir en oppklaring når det kommer til _range_.

**Comment by hmarthinsen** [comment]
Det høres bra ut! Håkon Marthinsen, SINTEF.

**Comment by johahaug** [comment]
Jeg har kikket litt på dette, og foreslår følgende: 

```
bilde,bilete,image,"I mange tilfeller kan termene bilde og verdimengde brukes synonymt. Hva som er vanlig ordvalg, avhenger av kontekst."
verdimengde,verdimengd,range,"I mange tilfeller kan termene verdimengde og bilde brukes synonymt. Hva som er vanlig ordvalg, avhenger av kontekst.<br><br>Verdimengde kan også omtales som bildemengde (bokmål) og biletmengd (nynorsk) eller rekkevidde (bokmål) og rekkjevidde (nynorsk)."
```

Forslaget innebærer å slette den nåværende oppføringen av bilde,bilete,image.

**Comment by johahaug** [comment]
Disse endringene er gjort, og jeg lukker denne tråden.
