### ISSUE TITLE
Coset: Endre "restklasse" til "sideklasse"

### ISSUE THREAD

**Issue by robinfissum** [jfremstad/matematisk_ordliste#53]
Hei! Synes oversettelsen av Coset bør endres fra "restklasse" til "sideklasse" :) Eventuelt bare tilføye dette

**Comment by jfremstad** [comment]
Hei! Har du noen kilder på at "sideklasse" brukes? Jeg har selv aldri hørt noen si dette og jeg finner heller [ingen relevante treff](https://www.nb.no/search?q=sideklasse&mediatype=b%C3%B8ker) i litteraturen. Restklasse derimot gir [mange treff](https://www.nb.no/search?q=restklasse&mediatype=b%C3%B8ker) i matematisk litteratur.

**Comment by robinfissum** [comment]
Hei. 
Man finner begrepet sideklasse flere plasser i litteraturen, https://matematikk.net/side/Gruppeteori , http://people.math.aau.dk/~leif/undervisning/Grupper2013/alg05.pdf .

Til og med den svenske wikipediasiden for Coset oversetter coset til Sidoklass , altså det som på norsk tilsvarer Sideklasse. https://sv.wikipedia.org/wiki/Sidoklass

En av grunnene til at jeg mener at dette bør endres er at en restklasse er en spesiell type sideklasse det snakkes om i tallteori og algebra, nemlig mengden bestående av alle heltall som gir samme rest ved divisjon med et forhåndsbestemt naturlig tall n. Sideklasse derimot, er et mer generelt begrep som omhandler resultatet av å kombinere ett spesifikk element med hvert element i en gitt mengde. 

Det er blant annet derfor man bruker begrepene høyre og venstre sideklasse for å spesifisere om man har kombinert mengden og det aktuelle elementet på høyre eller venstre side: a+S eller S+a.

F.eks. I lineær algebra: Dersom P representerer et plan som går gjennom origo og v er en vektor som ikke ligger i planet P vil P+v og v+P begge være samme mengde; planet P parallellforsjøvet langs v. Mengdene er like fordi vektoraddisjon er kommutativ. I algebra derimot trenger ikke operasjonen det er snakk om være kommutativ, og begrepene H/V sideklasse brukes. 

Mvh Robin Fissum

**Comment by johahaug** [comment]
Takk for interessant innspill, Robin. Jeg var ikke klar over at noen kaller dette for sideklasse. 

Som @jfremstad nevner, er oversettelsen restklasse svært etablert på norsk, og jeg vil være skeptisk til å fjerne denne. Mange bruker denne oversettelsen både om restklasser i Z modulo et naturlig tall n, og i det mer generelle tilfellet der man ser på restklassene til en undergruppe H av en generell gruppe G. Det er også vanlig å snakke om venstre og høyre restklasser (i samme betydning som venstre og høyre sideklasser, slik du beskriver). 

Det er imidlertid interessant at sideklasse er i såpass utstrakt bruk på dansk. Det er for meg ikke helt klart om sideklasse eller restklasse er vanligst på dansk. Restklasse gir treff i [Den Store Danske](http://denstoredanske.dk/It,_teknik_og_naturvidenskab/Matematik_og_statistik/Regning,_algebra_og_talteori/restklasse), noe sideklasse ikke gjør. Dette kan likevel tenkes å være fordi man, som du sier, ser ut til å typisk snakke om sideklasser på et høyere abstraksjonsnivå. 

Jeg ser at man også på tysk snakker om [Nebenklassen](https://de.wikipedia.org/wiki/Gruppentheorie#Nebenklassen), som svarer til sideklasse.

Jeg har ikke lyktes i å finne norske kilder som bruker oversettelsen sideklasse, til tross for at vi finner det på andre språk. Vet du om noen norske kilder, Robin? 

Selv om jeg ikke ville anbefalt å fjerne restklasse, er det mulig å vurdere om vi bør legge inn sideklasse som synonym, eller eventuelt som et eget oppslagsord der vi i en merknad påpeker nyanseforskjellen mellom oversettelsene restklasse og sideklasse.

**Comment by robinfissum** [comment]
Følgende er tatt fra Matematisk Leksikon, kunnskapsforlaget. Originalutgave 1997.: 

![1](https://user-images.githubusercontent.com/44507283/54658759-63872e00-4acf-11e9-94ab-0fd1cea78146.jpg)
![2](https://user-images.githubusercontent.com/44507283/54658760-641fc480-4acf-11e9-82fb-016f0b08f7ab.jpg)
![3](https://user-images.githubusercontent.com/44507283/54658761-641fc480-4acf-11e9-9522-7af16e44a437.jpg)
![4](https://user-images.githubusercontent.com/44507283/54658764-641fc480-4acf-11e9-88c6-27025f494de5.jpg)

**Comment by johahaug** [comment]
Takk for kilde. Jeg skal diskutere dette med noen av de andre ansatte i algebragruppa her ved NTNU, og komme tilbake med et forslag til hvordan vi bør føre opp sideklasse.

**Comment by johahaug** [comment]
Jeg har nå snakket med de fleste av de ansatte i algebragruppen ved NTNU, og det er ingen av dem som har hørt oversettelsen sideklasse i bruk. De fleste er imidlertid enige om at oversettelsen sideklasse gir god mening. Vi har også sett at oversettelsen brukes på [matematikk.net](https://matematikk.net/side/Gruppeteori). 

Jeg foreslår at vi endrer den nåværende oppføringen av restklasse til: 

```
restklasse/sideklasse,restklasse/sideklasse,coset / residue class,"Begge oversettelsene kan brukes på norsk, men restklasse er vesentlig mer utbredt."
```

Jeg fører deg opp på lista over bidragsytere, @robinfissum. Har du en tilhørighet til en utdanningsinstitusjon eller lignende som jeg skal ta med?

**Comment by robinfissum** [comment]
NTNU Gløshaugen. Tror du er algebralæreren min nå om jeg ikke tar helt feil.
[Ikke gi meg stryk da ! x) ]

**Comment by johahaug** [comment]
Aha, stemmer! Av nysgjerrighet: Hvor ble du først kjent med oversettelsen sideklasse? Jeg har inntrykk av at dette først og fremst har vært brukt på dansk eller av folk med dansk bakgrunn.

**Comment by robinfissum** [comment]
Det husker jeg faktisk ikke. Var nok i forbindelse med direkte summer i lineær algebra med anvendelser, men husker ikke nøyaktig hvor. :)

**Comment by johahaug** [comment]
Jeg tar med forslaget i neste runde som skal verifiseres, og lukker denne tråden.
