### ISSUE TITLE
Oversettelse av _embedding_

### ISSUE THREAD

**Issue by johahaug** [jfremstad/matematisk_ordliste#58]
Som @bowre nevner i #47, står oppslaget 
```
imbedding,imbedding,embedding,
```
oppført i ordlista. Denne oversettelsen er til en viss grad etablert og brukes f.eks. i en del [eksamensoppgaver](https://wiki.math.ntnu.no/_media/tma4190/2014v/eksammai2014.pdf), i artikler tilknyttet [Abelprisen](http://www.abelprisen.no/c63475/binfil/download.php?tid=63550) og står også oppført i Teknisk engelsk-norsk ordbok, se bilde:

![image](https://user-images.githubusercontent.com/25131491/54666955-7a3b7e00-4aeb-11e9-8dac-fa41ede031d2.png)

Oversettelsen brukes også i boka _[Topologi](https://www.nb.no/items/a67ffeadbdcb1a25cc699e46f1836c26?page=0&searchText=imbedding)_  av Per Holm og John Reed.

Jeg tror likevel mange er enige i at dette ikke er en optimal norsk oversettelse, og den har først og fremst blitt ført opp fordi vi ikke har lyktes i å finne noe godt alternativ. Er det noen som har forslag til en bedre oversettelse?

**Comment by robinfissum** [comment]
For å prøve å komme med et konstruktivt forslag, hva med " X er plantet i Y " ?

1. Dette ordet er ikke i bruk fra før av så vidt jeg vet
2. Ordet embedding inneholder ordet "bed", så man kan lage huskeregelen:
Embedding --> FlowerBED --> X is planted in Y --> X er planter i Y
3. En blomst / mengde blomster i et blomsterbed utgjør jo en delstruktur av blomsterbedet som helhet, så at X er plantet i Y gjenspeiler jo på en måte at X er 'inneholdt' i Y   
4. Ordet er delvis morsomt, og kanskje derfor lett å huske på 

Synes personlig den var morsom. Andre forslag er bla. "innestengt i" og "innrammet i". 
:)

**Comment by Tallak** [comment]
Jeg er enig i at imbedding er en dårlig oversettelse da det er vanskelig å forstå for noen som er nye i feltet og selve ordet gir lite intuisjon for de fleste.
Jeg tenker det er sentralt at ordet blir naturlig å bruke, som adverb, adjektiv og verb. Altså at "X is embedded in Y", "we embed X in Y" og "f is an embedding" blir naturlige uttrykk, og at oversettelsen er den samme for alle disse.
Med dette i bakhodet blir mange av forslagene problematiske spesielt når vi skal beskrive at f er en "embedding".
Forslag jeg her kommet over så langt er: innkapsling, innhylning, innebygning, omfavning.
Altså "X er innkapslet i Y", "vi innkapsler X i Y" og "f er en innkapsling".
"X er innhyllet i Y", "vi innhyller X i Y" og "f er en innhylning".
"X er innebygd i Y", "vi innebygger X i Y" og "f er en innebyggning".
"X er omfavnet av Y","Y omfavner X", "vi lar Y omfavne X" og "f er en omfavning".

Ser også at forslaget innramming over kan virke naturlig.
"X er innrammet i Y", "vi innrammer X i Y" og "f er en innramming".

Personlig og blant mine bekjente er omfavning den mest populære da en embedding er en fin og "myk" avbildning og omfavning fanger opp dette.

Videre mener jeg at hvorvidt en foreslått oversettelse er brukt tidligere i faglitteratur er litt irrelevant, og jeg vil heller ha fokus på hvorvidt uttrykket er naturlig, forståelig og gir intuisjon.

**Comment by robinfissum** [comment]
Jeg må si jeg synes forslaget "Innebygd" er egentlig veldig bra, fordi med ordbruken " X er innebygd i Y " er det det jo først og fremst opplagt at hva enn X er, så er det på en "naturlig måte" inneholdt i Y, men 'innebygd' betyr jo (i språk) også at strukturen til X er innehold i strukturen til Y.  Altså: Dette ordet virker som en naturlig utvidelse av 'inneholdt i ' fra set inklusjon til "Embedding". 

For å ta et konkret eksempel: Det er en "embedding" F fra kroppen av reelle tall til underkroppen R* av de komplekse tallene C (bestående av andre komponent lik null). Det er jo da intuitivt å si at "R er innebygget i C".     Bare min mening : )

**Comment by bervinator** [comment]
Denne termen skulle vi gjerne ha fornorsket. Vi takker derfor for deres engasjement! Nå har vi mange forslag å velge fra.

Vi har vært i kontakt med en høytstående norsk professor. Han mener at følgende oversettelser har vært i bruk:
- innleiring
- innbaking
- innlegg

Alle disse har åpenbare verbformer. Et annet alternativ han nevnte var innbedding, der samsvarende verb i infinitiv er å bedde.

Jeg er enig i at innebygging kan fungere bra som oversettelse. Vi snakker jo om en strukturbevarende avbildning.

**Comment by bervinator** [comment]
To geometere i Oslo har tatt kontakt på mail og foreslått embedding eller innleiring. Begrunnelsen er at imbedding kun er US-engelsk, og slettes ikke norsk. Embedding fungerer på begge engelske varianter og er brukt på norsk, selv om innleiring er et bedre norsk alternativ.

**Comment by johahaug** [comment]
Jeg liker forslaget innebygging. Innleiring er jo også fin norsk, selv om det for meg høres litt mer gammelmodig ut. Hva med å føre opp innebygging og innleiring (og tilhørende verb- og adjektivformer) som synonymer og påpeke i merknad at både embedding og imbedding også er i bruk på norsk?

**Comment by bervinator** [comment]
Jeg tar @johahaug  forslag videre til verifisering. Alle former anerkjennes, men det gis klare anbefalinger.

**Comment by bervinator** [comment]
Noen små grammatiske betraktninger gjenstår, men vi er så godt som i mål.
