### ISSUE TITLE
Proper functions

### ISSUE THREAD

**Issue by nicohasa** [jfremstad/matematisk_ordliste#6]
**Forslag:**
Anstendig funksjon, anstendig funksjon, proper function

**Merknad:**
Proper blir ofte oversatt til "ekte" (proper subspaces -> ekte underrom), men dette gir mindre mening for "proper function".

**Kommentar:**
 Vet at folk har kalt det propre funksjoner på norsk, men det virker ikke som godt norsk. Termen ble diskutert blant masterstudenter på UiO for noen år siden, anstendig virker som en god oversettelse av "proper" i denne sammenheng.

**Comment by jfremstad** [comment]
Godt forslag! Her synes også jeg at *proper* ikke høres ut som god norsk, men etter litt leting viser det seg at det faktisk har et oppslag i [ordboka](https://ordbok.uib.no/perl/ordbok.cgi?OPP=proper&ant_bokmaal=5&ant_nynorsk=5&begge=+&ordbok=begge). I tillegg ser jeg at det på tysk kalles [*eigentliche Abbildung*](https://de.wikipedia.org/wiki/Eigentliche_Abbildung) som direkte oversatt blir *egentlig/essensiell avbildning*. Alt dette gjør at jeg blir litt i tvil om *anstendig* er den beste oversettelsen, men jeg er så klart åpen for andre argumenter, for det er i grunnen et godt forslag du har kommet med.

**Comment by nicohasa** [comment]
En 'proper function' er en funksjon som oppfører seg ganske pent (behaves properly), jeg mener at ordentlig/anstendig høres bedre ut på norsk enn proper, selv om det teknisk sett er i ordboka. 'Ordentlig funksjon' høres litt teit ut, og er derfor mer for 'anstendig funksjon'. 'En egentlig funksjon' høres bare rart ut, og den er ikke essensiell som sådan.

Man kan fortsette å kalle det propre funksjoner, men for meg virker det som noe man gjør fordi man fornorska det engelske navnet og det heldigvis var et norsk ord som passa som ingen bruker. Virker da bedre å bytte ut med et mer brukt norsk ord som får frem samme idé.

**Comment by jfremstad** [comment]
Du kommer med gode poeng, og jeg vil si du har klart å overbevise meg. Jeg legger til termen i verifiseringsgreina, men jeg holder tråden oppe enn så lenge, da jeg ser for meg at det er flere som har meninger om denne termen.

**Comment by johahaug** [comment]
Personlig er jeg positiv til oversettelsen "anstendig funksjon", spesielt med utgangspunkt i argumentet om at dette er snakk om funksjoner som på et vis oppfører seg "slik man burde forvente". 

Som med andre mer kontroversielle oversettelser, er nok dette et eksempel der vi vil kunne møte motstand fra fagfolk som "i alle år" har kalt det "propre" funksjoner. Jeg husker selv å ha diskutert denne oversettelsen med en professor for noen år siden, og han mente bestemt at proper var det man burde kalle det. Et alternativ kan være å føre opp proper funksjon og anstendig funksjon som synonymer, kanskje med merknad om at anstendig funksjon er anbefalt oversettelse, men da "tillater" vi samtidig oversettelsen "proper". 

Siden vi her foreslår en oversettelse som, såvidt jeg vet, er helt "ny", ville det være fint om vi kunne luftet forslaget med flere fra fagfeltet. Har du snakket med mange som er positive til denne oversettelsen, @nicohasa?

**Comment by johahaug** [comment]
Jeg foreslår at vi fører opp anstendig avbildning, som foreslått av @nicohasa, som oppslagsord, med merknaden "Oversettelsen proper avbildning (bokmål) og proper avbilding (nynorsk) er også i bruk, men denne er ikke anbefalt."

**Comment by johahaug** [comment]
Vi har ført opp denne oversettelsen som foreslått i første innlegg på denne tråden, og med merknad om proper også er i bruk. Termen vil gå gjennom en verifiseringsrunde før den legges ut på den offisielle ordlista. 

Når noen har kommet med forslag eller innspill som bidrar til endringer/forbedringer av ordlista, legges de til i lista over bidragsytere. @nicohasa: Hvis du oppgir navn (og gjerne eventuell tilhørighet til utdanningsinstitusjon etc.), blir du lagt til som bidragsyter.
