### ISSUE TITLE
Oversettelse av ordet "cusp"

### ISSUE THREAD

**Issue by robinfissum** [jfremstad/matematisk_ordliste#66]
Forslag om å legge til ordet "cusp" og tilhørende norsk oversettelse til på lista. 

En cusp (i matematisk forstand, på engelsk) er et punkt på en kontinuerlig deriverbar curve f : [0,1]->R^n hvor f ' (x) = 0. 

Ser at på https://nn.wikipedia.org/wiki/Spiss_i_matematikk
og https://snl.no/spiss_-_matematikk 
så er den norske oversettelsen "spiss".

**Comment by johahaug** [comment]
Godt poeng, en oversettelse av _cusp_ bør med. For meg høres spiss greit ut, men jeg har sendt spørsmålet videre til noen i analysegruppa ved NTNU. Jeg legger ut ny melding når de har fått diskutert termen.

**Comment by johahaug** [comment]
Jeg har nå fått følgende tilbakemelding: Ingen vi har vært i kontakt med har hørt noe annet enn spiss i bruk på norsk, men mange er likevel enige om at det høres litt "rart" eller "upresist" ut. Situasjonen minner om oversettelsen av _curl_: Her finnes det gode språklige argumenter for å oversette til rotasjon, og det gjøres slik på f.eks. svensk og tysk. Likevel er det nok vanligst at de fleste på norsk bare sier curl. 

Tilsvarende som i oppslaget for _curl_ foreslår jeg derfor at vi fører opp: 

```
spiss,spiss,cusp,"Cusp brukes også på norsk, men spiss anbefales."
```

**Comment by robinfissum** [comment]
Høres bra ut :)

**Comment by johahaug** [comment]
Jeg legger inn dette blant termene som skal med i neste verifiseringsrunde og lukker denne tråden. Hvis noen har flere innspill, er det bare å åpne tråden igjen.
