### ISSUE TITLE
ligning vs likning

### ISSUE THREAD

**Issue by helgeholden** [jfremstad/matematisk_ordliste#67]
Jeg foreslår at konvensjonen
  Likning benyttes fremfor ligning.
fjernes, og at "ligning" benyttes på bm og "likning" benyttes på nn. 
Grunnene er følgende.
1. "ligning" er normalformen på bokmål. Se https://www.naob.no
2. Det virker urimelig å fjerne et ord som er i standard bruk, og trolig
benyttes av de fleste norsktalende.
3. Selv om det er praktisk å ha samme ord på bm og nn, strider mot 
andre konvensjoner:  "..unngå bokmålsnære former som ikke har 
tradisjon i nynorsk."

**Comment by jfremstad** [comment]
Hei! Jeg ser ingen vesentlig grunn til å endre denne konvensjonen.

1. Ligning og likning er [sidestilte på bokmål](https://ordbok.uib.no/perl/ordbok.cgi?OPP=likning).
2. Hvis man søker i [Nasjonalbibliotekets litteraturdatabase](https://www.nb.no/), så får man betydelig flere treff på likning enn på ligning.
3. Konvensjonen du refererer til sier noe om hvordan man velger ord på nynorsk, noe som er irrelevant da det på nynorsk skal det være likning.

**Comment by helgeholden** [comment]
Jeg er litt overrasket over fremgangsmåten her.
Du svarer og sier at du har bestemt deg, og så stenger du saken.
Er det så enkelt?
Hvorfor kan ikke den ligge fremme så andre eventuelt kan uttale seg?

Mitt argument om hvordan dere velger ord på nynorsk viser at det ikke
benyttes samme logikk som dere bruker på ligning vs likning.

Det ville være en konsekvent konvensjon alltid å bruke samme ord på
bm og nn der det var mulig. Det ville føre til noen litt uvanlige ord (både
på bm og nn), men det ville være konsekvent. Men det gjør du altså ikke.

Helge Holden

**Comment by jfremstad** [comment]
Selv om en tråd er lukket ligger den fortsatt ute og det er derfor ingenting i veien for å fortsette å diskutere på den, eller åpne den om du føler du har mer å tilføye.

Basert på argumentene i din opprinnelige post så synes jeg ikke dette er nok til å endre på konvensjonen. Kort oppsumert er første punkt feil, og andre punkt gjelder like mye for både likning og ligning. I siste punkt så tror jeg du har misforstått hva konvensjonen sier. Den sier ingenting om valg av bokmålsord og er derfor ikke relevant for valg av ligning/likning på bokmål.

**Comment by helgeholden** [comment]
Jeg kan fortsatt ikke forstå hvorfor ikke “ligning” kan innføres som alternativ til “likning” på bokmål. Mange steder
er det gitt flere alternativer, f.eks.
bm: beskrivende statistikk / deskriptiv statistikk
nn: beskrivande statistikk / deskriptiv statistikk / skildrande statistikk

Det virker urimelig å fjerne et alminnelig brukt ord, og inntrykk av at det ikke eksisterer eller er i bruk.
 
Helge Holden

**Comment by johahaug** [comment]
Jeg er enig med Helge i at det er hensiktsmessig å la tråder som denne stå åpne en stund, slik at flere som har tanker kan få uttalt seg. Det er positivt at diskusjonsforumet brukes, og terskelen bør være lav for å legge inn innlegg. Det virker derfor fornuftig å ikke lukke tråder før trådstarter og andre interesserte har kommet med sine meninger. 

Jeg synes det ville vært dumt å ha som konvensjon å bruke samme skrivemåte på bokmål og nynorsk i tilfeller der dette er mulig. Som Helge sier: Dette ville gitt mange uvanlige ordvalg og skrivemåter på begge målformer. Så langt har vi arbeidet ut fra at ordvalg og skrivemåte på hver målform bør velges separat. Hvordan ordet skrives på nynorsk har altså ikke hatt betydning for den nåværende konvensjonen om å bruke skrivemåten likning på bokmål. La meg si litt mer om hvilke tanker som ligger bak denne konvensjonen, og hvorfor vi ikke har lagt inn ligning som alternativ. 

I veldig mange tilfeller er det flere mulige skrivemåter som samsvarer med norsk rettskrivning. På nynorsk kan man f.eks. velge om man vil skrive rekkje/rekke, bølgje/bølge eller linje/line. Tilsvarende er likning og ligning sidestilte skrivemåter på bokmål. For å vise et mer ekstremt eksempel er både delbrøkoppspalting, delbrøkoppspaltning, delbrøksoppspalting og delbrøksoppspaltning helt lovlige skrivemåter. 

Vi har konsekvent valgt å la være å føre opp forskjellige tillatte skrivemåter i ordlista. Jeg mener dette er viktig, da ordlista ellers ville blitt veldig uoversiktlig og mindre brukervennlig. Å føre opp delbrøkoppspalting/delbrøkoppspaltning/delbrøksoppspalting/delbrøksoppspaltning som oversettelse, vil gi veldig lite interessant informasjon til brukere av ordlista. 

I tilfellet _beskrivende statistikk / deskriptiv statistikk_ er det snakk om synonymer, og altså ikke kun om ulike skrivemåter, noe som er en stor forskjell. Jeg mener det vil være en dårlig løsning å føre opp begge skrivemåtene ligning og likning for alle oversettelser der dette ordet inngår. Hvis vi skal være konsekvente, ville dette innebære at vi bør føre opp alle tillatte skrivemåter også i alle andre tilfeller, noe som etter min mening er veldig lite hensiktsmessig. 

I ordlistas språklige konvensjoner presiseres det at det at en skrivemåte brukes gjennomgående ikke betyr at andre tillatte skrivemåter frarådes, men at det snarere er et valg som er gjort for å gjøre ordlista mer brukervennlig. Det kan selvsagt argumenteres for at dette er uheldig, da det til en viss grad signaliserer at den valgte skrivemåten bør foretrekkes. Likevel mener jeg at alternativet, altså å alltid føre opp alle mulige skrivemåter, er langt verre. 

Det kan også nevnes at søkefunksjonen er programmert slik at også søk på ligning gir treff (bl.a. for å forsøke å forhindre at likning oppfattes som eneste lovlige skrivemåte).

**Comment by hanche** [comment]
Ordet *likne* kom inn i bokmål i 1917, og ble sidestilt med *ligne* i 1938 ([kilde](https://www.sprakradet.no/svardatabase/sporsmal-og-svar/nar-kom-skrivematen-likne-inn-i-bokmal/)). Dette er jo de to store samnorsk-reformene. Som kjent var samnorsk-prosjektet dødfødt i det lange løp, selv om en del bruksmåter henger igjen fra den tiden.

I senere år har man operert med hovedformer og sideformer, og en læreboknormal. Jeg har ikke klart å finne ut hva læreboknormalene har å si om ligning/likning, og uansett er vel de utdatert nå. Begrepet hovedform/sideform forsvant fra offisielt bokmål i 2005 ([kilde](https://www.allkunne.no/framside/sprak/omgrep/hovudformer/67/1351/)). Men om vi ser på hvordan bokmålsordboka presenterer ordene ([her](https://ordbok.uib.no/perl/ordbok.cgi?OPP=+ligning&ant_bokmaal=5&ant_nynorsk=5&bokmaal=+&ordbok=bokmaal)), får man avgjort inntrykk av at *ligning* er det primære ordet. Man får akkurat det samme om man søker på *likning* i stedet.

Til sist: Jeg er ikke så sikker på at et søk på de to ordene i nasjonalbibliotekets database er et godt kriterium, men jeg får i hvert fall betydelig flere treff på [ligning](https://www.nb.no/search?q=ligning) enn på [likning](https://www.nb.no/search?q=likning).

Alt i alt vil jeg nok heller satse på *ligning* i ordlisten, men for all del, la også søk på *likning* føre frem.

**Comment by jfremstad** [comment]
> Til sist: Jeg er ikke så sikker på at et søk på de to ordene i nasjonalbibliotekets database er et godt kriterium, men jeg får i hvert fall betydelig flere treff på ligning enn på likning.

Man får flere treff på [likning](https://www.nb.no/search?q=likning&mediatype=b%C3%B8ker&ddc=51) enn på [ligning](https://www.nb.no/search?q=ligning&mediatype=b%C3%B8ker&ddc=51) hvis man begrenser søket til matematikk-litteratur.

**Comment by helgeholden** [comment]
Det er ikke så lett å sammenligne bruken av ligning vs likning, siden, som johahaug sier, "Det kan også nevnes at søkefunksjonen er programmert slik at også søk på ligning gir treff (bl.a. for å forsøke å forhindre at likning oppfattes som eneste lovlige skrivemåte)."

Wikipedia bruker "ligning" på bokmål (men skriver at man også kan bruke "likning") og "likning" på nynorsk. 

Jeg synes ikke at argumentet om at "ligning" droppes for å gjøre ordlisten mer brukervennlig er et godt argument.  Om ønsket er at ordlisten skal være normerende, så er det lurt ikke å droppe former som er helt vanlige for å gjøre den mer brukervennlig. Søker man på "ligning" eller "ligning" kommer man til en og bare en form på bokmål, nemlig "likning", og det mener jeg er uheldig og misvisende, og svekker tiltroen til et ellers flott initiativ.

**Comment by johahaug** [comment]
Bare en kort oppklaring: Jeg snakker om søkemotoren til ordlisten, hvor det er lagt inn at søk på ligning skal gi treff. Dette gjelder ikke for Nasjonalbibliotekets bokbase. Søkene @jfremstad viser til herfra er altså sammenlignbare, og viser at skrivemåten likning totalt sett er mer brukt i matematisk litteratur enn skrivemåten ligning. Nasjonalbibliotekets bokbase er den beste kilden vi har tilgang til for å kartlegge utbredelse av ulike skrivemåter i eksisterende litteratur. 

Samtidig er det riktig, som dere nevner, at en del nettsider og andre kilder bruker ligning. Siden formene regnes som sidestilte, er det ikke veldig overraskende at begge skrivemåter er mye brukt både i matematisk litteratur og andre steder. Ettersom begge skrivemåtene er lovlige og i utstrakt bruk, vil innvendingen om at den utelatte skrivemåten burde vært med være aktuell uavhengig av hvilken skrivemåte ordlisten bruker. Dersom vi går over til å kun føre opp ligning, vil det altså være like aktuelt å stille spørsmål ved hvorfor skrivemåten likning ikke er tatt med. 

Dersom vi går for å føre opp både ligning og likning, har du noe forslag til hva som bør gjøres for andre oversettelser der det er flere tillatte skrivemåter, @helgeholden? Jeg tenker at det er viktig å ha retningslinjer som det er mulig å følge mest mulig konsekvent.

**Comment by hanche** [comment]
> Man får flere treff på [likning](https://www.nb.no/search?q=likning&mediatype=b%C3%B8ker&ddc=51&languages=nob) enn på [ligning](https://www.nb.no/search?q=ligning&mediatype=b%C3%B8ker&ddc=51&languages=nob) hvis man begrenser søket til matematikk-litteratur.

Aha. Jeg så på hjelpesidene at de skulle ha en filtreringsfunksjon, men jeg klarte ikke å finne den. Svaret er at man må klikke seg vekk fra **Alt** til **Bøker**, **Aviser** eller **Tidsskrift** for å få tilgang til slike filtere.

Uansett, så var det jo bra at jeg tok forbehold om nytten av en slik opptelling. (Og overvekten av *likning* er uansett ikke overveldende, selv om den er klar.) Men for å utdype min skepsis litt: Den overveiende delen av treffene ser ut til å være lærebøker, og der er det nok forlagene som i stor grad har bestemt ordvalget. Jeg ser for eksempel bøkene til Alfsen og Alfsen på «likning»-siden. Den yngre av de to forfatterne var min veileder, og jeg har litt vanskelig for å tenke meg at han skrev *likning* helt frivillig. Her kommer vi kanskje tilbake til påvirkningen fra læreboknormalen, men den har jeg ikke noen mulighet for å sjekke.

Går man til avisene, er det stor overvekt av *ligning*, men det har åpenbart med ligningsvesenet å gjøre, ikke matematikk. Så det skal ikke veie så tungt, det heller.

**Comment by helgeholden** [comment]
For å svare @johahaug:
Jeg tror det er vanskelig å være helt konsekvent siden språket selv ikke er det. Når språk er sensitivt i Norge, og staving av ord er viktig for mange, er det nødvendig at matematisk ordliste aksepterer det, og  ikke selv bestemmer hva som ville være en fornuftig eller rimelig staving av ord.  
Om ordlisten inneholder mange (lovlige) alternativer, blir den ikke mindre brukervennlig, men det motsatte. Ordlisten skal ikke leses, men brukes til oppslag, og da forventes det å finne lovlige former.
Særlig gjelder det ord som har et liv utenom matematikken, som ligning, rekke, bølge, osv. Så der ville jeg inkludere alle lovlige former. For andre ord ville jeg være mer fleksibel.
Så for ligning mener jeg det bør stå:
bm   ligning/likning
        differensialligning/differensiallikning [tilsvarende for andre ord av samme type]
nn   likning
       differensiallikning [tilsvarende for andre ord av samme type]

**Comment by johahaug** [comment]
Jeg stiller meg skeptisk til dette forslaget, i alle fall hvis vi mener det som en gjennomgående konvensjon. Dersom vi skulle etablert som retningslinje at ordlista bør forsøke å omfatte _alle_ eller _flest mulig_ lovlige oversettelser og skrivemåter, er det verdt å understreke at en slik endring ville berørt veldig, veldig mange oppslagsord. Sånn sett er dette et mye mer grunnleggende spørsmål enn kun en diskusjon av skrivemåtene likning og ligning (det ville være lettere å gjøre et unntak for enkeltord som ligning/likning, enn å endre strukturen til hele ordlista). 

Før det eventuelt iverksettes en så omfattende endring, tenker jeg det kan være lurt å reflektere litt over hvilke behov en liste med oversettelser av fagterminologi primært bør dekke. Slik jeg ser det, er det viktigste målet med et prosjekt av denne typen å utvikle et verktøy som gjør det lettere å kommunisere om matematikk på norsk. Forhåpentligvis vil dette kunne bidra til at man unngår svært dårlige eller manglende oversettelser, noe som dessverre er relativt utbredt. Jeg mener at denne typen lister med oversettelser først og fremst bør tenkes på som et _hjelpemiddel_, og ikke primært som normerende når det kommer til rettskriving. Såvidt meg bekjent er det heller ingen termlister fra andre fagfelt som tar sikte på å ha med alle gyldige skrivemåter. Se [her](https://www.sprakradet.no/Sprakarbeid/Terminologi/termlister-og-termbaser/) for en liste over tilsvarende arbeid gjort innenfor andre fagområder. Se også [her](http://www.termwiki.sprakradet.no/wiki/Hovedside) for lister med oversettelser som bruker Språkrådets oppsett for termlister. 

Er det noen grunn til at en matematisk ordliste bør inneholde mer informasjon knyttet til lovlige skrivemåter enn andre tilsvarende termlister? Jeg er absolutt enig i at det er viktig å ha tilgang til gode kilder som gir informasjon om hvilke skrivemåter som er i tråd med norsk rettskriving. Heldigvis har vi på norsk allerede en svært god normerende kilde på dette, nemlig [denne](https://ordbok.uib.no/). Det har mange praktiske utfordringer dersom en liste med oversettelser av faguttrykk skal forsøke å ha med like detaljert informasjon som Språkrådet sin ordliste.

Jeg kan om ønskelig komme tilbake med flere eksempler for å illustrere hvorfor det vil være utfordrende med en konvensjon om at alle akseptable oversettelser eller skrivemåter skal tas med, og hvorfor jeg mener dette ville redusert brukervennligheten. 

Kanskje @OleVaage eller @Langaker i Språkrådet har noen kommentar til hvordan det er vanlig å tenke om denne typen spørsmål i andre terminologiprosjekter?

**Comment by helgeholden** [comment]
At en endring i konvensjonene vil medføre mange endringer er ikke i seg selv et argument mot å gjøre det. Men det er en god grunn til å tenke seg om først.  Utgangspunktet er jo at norsk tillater mange ulike skrivemåter for samme ord, og det kan man ikke bare ignorere.

Mitt utgangspunkt er at det er nøyaktig to konvensjoner i bokmål for ordlisten:
"Frem benyttes i stedet for fram.
Likning benyttes fremfor ligning."
og jeg finner det urimelig og vilkårlig å fjerne "ligning" fra ordlisten.  Om man fjerner den konvensjonen, og gjør "ligning" og "likning" likestilte i bokmål, er jeg fornøyd, og skal ikke si noe mer.

Det er greit at listen skal være et hjelpemiddel, men å fjerne "ligning" fra listen virker urimelig og umotivert.  Selv om ordlisten aldri kan bli normgivende, så kan den i praksis få en slik funksjon. Og da mener jeg at et hyppig brukt ord som "ligning" må med.

**Comment by johahaug** [comment]
Dette er ikke noe som har blitt ignorert, men snarere noe som har vært grundig diskutert. Vi har vurdert det slik at det vil være svært lite hensiktsmessig å ta med alle mulige skrivemåter, og har forholdt oss til dette gjennomgående. For å lage en ordliste som denne er det helt nødvendig å gjøre _utvalg_ underveis. Først og fremst må det typisk velges ut én eller to blant potensielt mange mulige oversettelser, men i en del tilfeller er det også nødvendig å velge ut en mulig skrivemåte framfor en annen. I hvert enkelt tilfelle er dette forsøkt basert på det som finnes av skriftlige kilder, i tillegg til kommunikasjon med eksperter knyttet til hvert enkelt fagfelt og anbefalinger fra Språkrådet. Hovedmotivasjonen til at likning er skrevet framfor ligning er det betydningsmessige slektskapet til ord som _lik_ og _likhet_, som mange mener bør reflekteres i skrivemåten av likning. I tillegg kommer utbredelse i matematisk litteratur, som nevnt av @jfremstad. I en slik utvelgingsprosess vil det likevel inngå skjønnsmessige vurderinger som ikke nødvendigvis alle vil være enige i. Da tenker jeg det er bra at vi har et forum som dette, slik at alle brukere av ordlista kan komme med innspill og slik at det stadig kan gjøres forbedringer. 

Hvis vi mener at ordet ligning/likning skiller seg ut i den forstand at det er spesielt viktig at begge skrivemåter tas med i ordlista, kan jeg godt støtte et forslag om å se på dette som et unntak og legge inn begge skrivemåter gjennomgående. Vi har fram til nå ikke sett noen grunn til å tenke på dette ordet som et unntak, men bare det at personer som @helgeholden og @hanche ser det som problematisk at ligning ikke er med, bør vel kunne ses på som et tilstrekkelig godt argument. 

Jeg har gått gjennom de nåværende termene som inneholder -ligning, og såvidt jeg kan se ser ut som om det vil gå greit å legge inn begge alternativer, i den forstand at vi ikke vil støte på den typen utfordringer som en del steder vil oppstå dersom man velger å legge inn alle mulige skrivemåter. F.eks. vil vi faktisk ikke få oppslag der det inngår mer enn to alternativer på hver målform (til sammenligning ville et generelt prinsipp om at alle lovlige skrivemåter skal med, innebære at enkelte oppslagsord ville få hele 12 mulige skrivemåter kun på nynorsk). 

Forslaget er altså å legge inn både ligning og likning i alle tilfeller der ordet inngår. Fint om andre som har meninger om dette legger inn en kommentar om hvorvidt de synes dette høres ut som en grei endring.

**Comment by helgeholden** [comment]
Det er fint at dere vil se på om "ligning" kan sidestilles med "likning" overalt i bokmål. Som du skriver, vil ikke det medføre større problemer eller endringer.

Jeg synes ikke argumentet om slektskapet til "lik" og "likhet" er særlig godt; språket virker ikke slik. Det er mange ord som logisk sett skulle vært skrevet på en annen måte enn de faktisk blir skrevet. Og sånn er det bare. Uttalenærhet er et annet prinsipp som virker noen steder, men ikke alle steder.

snl.no bruker "ligning" [nevner ikke "likning"], Wikipedia bruker "ligning". 
Læreboken Søgaard og Tambs Lyche "Matematikk for den høgre skolen" som utdannet flere generasjoner realister skriver "ligning" [og var i bruk under samnorskperioden]. Lindstrøms "Kalkulus" bruker "ligning".

Og som fagperson innen differensialligninger finner jeg det fortsatt urimelig og vilkårlig å utelukke "ligning" fra ordlisten.

Jeg håper derfor at denne mindre endringen vil bli gjennomført.

**Comment by hanche** [comment]
Jeg har laget en [pull request](https://github.com/jfremstad/matematisk_ordliste/pull/68) med én måte å løse dette på.

**Comment by johahaug** [comment]
Da skal alle nødvendige endringer i forbindelse med dette være utført. Takk for innspill. 

Når noen har bidratt med forslag som har ledet fram til forbedringer av ordlista, pleier vi å legge dem til i lista over bidragsytere - så jeg legger deg til der, @helgeholden (@hanche er allerede ført opp). 

Såvidt jeg kan se, kan denne tråden da lukkes.
