### ISSUE TITLE
Similar matrices

### ISSUE THREAD

**Issue by oysteins** [jfremstad/matematisk_ordliste#7]
Jeg savner begrepet «similar» (om matriser) i ordlisten (se for eksempel Wikipedia-siden om [matrix similarity](https://en.wikipedia.org/wiki/Matrix_similarity)). Den eneste varianten av begrepet jeg har sett på norsk er «similær», men jeg synes ikke egentlig det høres så veldig bra ut.

**Comment by jfremstad** [comment]
Dette har vi på et tidspunkt diskutert litt i prosjektgruppa og forslagene som dukket opp var:

- Similær matrise
- Likedannet matrise
- Liknende matrise

Selv heller jeg litt mot *likedannet matrise*, da dette også beskriver en slik matrise ganske godt.

Jeg er veldig interessert i å høre om det finnes andre forslag.

**Comment by bowre** [comment]
Når man snakker om "similar matrices" er det ofte i forbindelse med "similarity transformation" som oversetter enklere til similærtransformasjon enn likdannettransform (eller hva det måtte bli). Tror også similære matriser er så etablert i matematikk at det neppe vil endre hva som brukes selv om det kommer et annet ord i ordlista. Så jeg setter pengene på similær :-).

**Comment by johahaug** [comment]
I boka _Lineær algebra og diskret matematikk_ av Stray og Ubøe brukes likedannete matriser som hovedform, men det påpekes at slike matriser også kalles similære. Boka ligger tilgjengelig på [bokhylla.no](https://www.nb.no/items/36e28e28fc50b960305e8eb6ef8dfe8e?page=0&searchText=%22likedannete%20matriser%22) (Nasjonalbiblioteket). I [dette](https://org.uib.no/mi/eksamen/MAT121/MAT121_2014_h_fasit_eksamen.pdf) løsningsforslaget fra en eksamen i lineær algebra ved UiB brukes også similær og likedannet synonymt. Dette antyder at begge disse variantene er i en viss bruk. Jeg finner ingen kilder som bruker "liknende matriser", så foreslår at vi i alle fall ikke går for dette. Et alternativ kan være å føre opp similær og likedannet som synonymer.

Jeg er enig i at similærtransformasjon nok virker som den mest naturlige oversettelsen av _similarity transformation_.

**Comment by bowre** [comment]
Et annet beslektet begrep er det som på engelsk heter isospectral som vel oversetter greit til isospektral på norsk. Men det er ikke helt det samme som similær.

**Comment by johahaug** [comment]
Enig i at isospektral virker som en helt fin oversettelse og at dette bør tas med. Vi legger det inn i neste verifiseringsrunde.

**Comment by johahaug** [comment]
Av termer nevnt i denne tråden, foreslår jeg at vi fører opp følgende: 

```
likedannet/similær,likedanna/similær,similar,"Oversettelsen gjelder bruk i lineær algebra og utelukker ikke at termen kan benyttes ulikt i andre sammenhenger."
likedannet matrise / similær matrise,likedanna matrise / similær matrise,similar matrix,
isospektral,isospektral,isospectral,
```
Kom gjerne med innvendinger eller forslag til bedre løsninger. 

Angående _similarity transformation_: På bokhylla.no får man vesentlig flere treff på similaritetstransformasjon enn på similærtransformasjon. Mener du at similærtransformasjon likevel bør foretrekkes, @bowre?

**Comment by johahaug** [comment]
Jeg har lagt inn likedannet/similær, likedannet matrise og isospektral som foreslått ovenfor til neste verifiseringsrunde. 

Det som gjenstår i denne tråden er altså oversettelsen av _similarity transformation_. Det virker som om similaritetstransformasjon er vesentlig mer brukt enn similærtransformasjon. Jeg foreslår derfor at vi legger inn similaritetstransformasjon som oversettelse. Høres dette greit ut, @bowre?

**Comment by johahaug** [comment]
Jeg legger til similaritetstransformasjon som forslag til neste verifiseringsrunde og lukker denne tråden. Som vanlig, bare å åpne tråden igjen hvis noen har ytterligere innspill.

**Comment by bowre** [comment]
Jada, jeg bøyer meg jo for ekspertisen 😀 og vet jo at dere sjekker dette på ulike måter ved søking etc.
Det er vel slik med de fleste av oss at vi bruker uttrykkene vi lærte av vår egen lærer, og det er jo ofte kun én person.
Men en kan kanskje mistenke at ordet similaritetstransformasjon er noe som kan se ut til å være oversatt litt fort og gæli fra engelsk.

Hilsen Brynjulf

On 23 Apr 2019, at 11:15, johahaug <notifications@github.com<mailto:notifications@github.com>> wrote:


Jeg har lagt inn likedannet/similær, likedannet matrise og isospektral som foreslått ovenfor til neste verifiseringsrunde.

Det som gjenstår i denne tråden er altså oversettelsen av similarity transformation. Det virker som om similaritetstransformasjon er vesentlig mer brukt enn similærtransformasjon. Jeg foreslår derfor at vi legger inn similaritetstransformasjon som oversettelse. Høres dette greit ut, @bowre<https://github.com/bowre>?

**Comment by johahaug** [comment]
Jeg ser faktisk nå at også likedannethetstransformasjon brukes i noen få kilder, men er forsåvidt enig i at det blir noe tungt. Similaritetstransformasjon er jo også tyngre enn similærtransformasjon, som jo kan være et argument for sistnevnte. 

Nærmere spesifisering av søkene som er gjort:
Et søk på Nasjonalbibliotekets søkesider gir [20](https://www.nb.no/search?q=similaritetstransformasjon&mediatype=b%C3%B8ker) treff på similaritetstransformasjon, mot ingen treff på similærtransformasjon. Nå skal det sies at ingen av kildene som bruker similaritetstransformasjon er rent matematiske. Likevel antyder det jo en viss utberedelse. Ellers er f.eks. [denne](https://www.cs.hioa.no/~halvarf/Matte1000_16V/Notater/Bok_LinAlg%206%20utg-1.pdf) en relevant kilde som bruker similaritetstransformasjon og som ikke er med i Nasjonalbibliotekets bokbase. 

Man kan også merke seg at similærtransformasjon så godt som ikke gir treff heller ved et vanlig Google-søk, med unntak av et løsningsforslag fra 1994. 

Men @bowre, hvis du som fagperson mener at similærtransformasjon likevel er utbredt og er bedre, så kan man fint velge å legge mer vekt på det enn på det som finnes av skriftlige kilder. Som du sier, det at man har noen skriftlige kilder trenger på ingen måte bety at det er _gode_ kilder språklig sett.

**Comment by bowre** [comment]
Hei,

jeg melder pass her, vil absolutt ikke insistere. En mulighet er å ta en liten runde blant de mer senior matematikerne ved instituttet, som f.eks. Frode R., Kristian Seip, Helge H., Christian Skau, Kari, Sverre S. etc. Også Heidi Strømskag er interessert og kunnskapsrik når det gjelder språk.

-Brynjulf

On 3 Feb 2020, at 18:03, johahaug <notifications@github.com<mailto:notifications@github.com>> wrote:

Men @bowre<https://github.com/bowre>, hvis du som fagperson mener at similærtransformasjon likevel er utbredt og er bedre, så kan man fint velge å legge mer vekt på det enn på det som finnes av skriftlige kilder. Som du sier, det at man har noen skriftlige kilder trenger på ingen måte bety at det er gode kilder språklig sett.

**Comment by johahaug** [comment]
Vi forhører oss litt rundt og holder tråden åpen inntil videre.

**Comment by johahaug** [comment]
Jeg har snakket med Frode Rønning. Et viktig poeng her, som vi kanskje ikke har tenkt så mye på sålangt, er at _similarity transformation_ er et uttrykk som brukes både i euklidsk geometri og i lineæralgebra (med anvendelser).

I euklidsk geometri er dette en avbildning som bevarer formlikhet. Vi foreslår formbevarende avbildning som oversettelse i dette tilfellet. 

Jeg skal forhøre meg med flere om hva de mener er best i tilfellet der man snakker om matriser.

**Comment by johahaug** [comment]
Jeg har vært i kontakt med Helge og Kari. Helge sier han bruker similaritetstransformasjon, mens Kari synes det blir noe tungt og foretrekker similærtransformasjon. En mulighet kan være å føre opp de to formene som synonyme. Hva tenker du om en slik løsning, @bowre?

**Comment by bowre** [comment]
Det høres ut som en grei løsning hvis det tydelig framgår at forskjellige matematikere bruker litt forskjellige uttrykk. Men jeg skal innrømme at jeg kjenner litt på dette at oversettelser direkte fra engelsk synes å få veldig lett fotfeste fordi vi leser så mye engelsk litteraur. Det blir bare synsing fra min side, men en kan få assosiasjoner til denne tilbøyeligheten når man hører oversettelser som similaritetsttransformasjon. Et enda grellere eksempel: Flere flinke norske matematikere snakker om (...)morfismer i stedet for (...)morfier. Men som sagt: Løsningen du foreslår høres bra ut.

**Comment by johahaug** [comment]
Absolutt veldig enig! Og nettopp å unngå det er jo et av målene med ordlista. Likevel tenker jeg at det i akkurat dette tilfellet kan forsvares å ta med begge muligheter.

**Comment by bervinator** [comment]
Jeg er enig i at vi kan ta med begge muligheter her.

**Comment by bervinator** [comment]
Termene similaritetstransformasjon/similærtransformasjon og formbevarende avbildning videresendes til prosjektgruppen. Tråden lukkes, og åpnes igjen dersom disse skulle møte motstand.
