### ISSUE TITLE
Mange begreper fra algebraisk geometri

### ISSUE THREAD

**Issue by sorengam** [jfremstad/matematisk_ordliste#75]
Her er det en del forslag til termer som brukes i algebraisk geometri, og litt tanker om noen av dem.

**Stack:**

En norsk oversettelse kan være _stakk_ eller _stabel_.  Alternativt kan man oversette fra det franske originalbegrepet ’champ’ som betyr eng/mark/åker/felt. Standardoversettelsen (om man ikke bare sier _stack_ på norsk), ser for tiden ser ut til å være _stakk_.

**Flabby/Flasque:**

På Blindern, i hvert fall, brukes noen ganger _kvapsete_ som en oversettelse av dette begrepet (om knipper). Ellers er det temmelig nytt – og ikke overalt akseptert – å bruke ordet _flabby_ på engelsk. For eksempel bruker ’The Stacks project’ "flasque sheaf", men nevner at "flabby sheaf" er et synonym. (https://stacks.math.columbia.edu/tag/09SV)

**Grassmannian:**
Det burde være greit å bruke _grassmann_ (m.) som norsk oversettelse. Som flertallsform har jeg hørt og selv brukt _grassmenn_.

**GIT quotient:**
Hva med å bruke _gitkvotient_? Forkortelsen GIT står for ’geometric invariant theory’ på engelsk, men det kan jo like gjerne være ’geometrisk invariantteori’ på norsk.

**Étale:**
Dette begrepet brukes på engelsk som et lånord direkte fra fransk, og slik er det på norsk også.
Utover den matematiske bruken er det et temmelig obskurt ord på fransk, som så vidt jeg kan finne ut betyr ’stillestående’, og brukes i maritime sammenhenger.
Forslag til norsk oversettelse: _stillestående_, _rolig_. Det er sikkert mange bedre ord som jeg ikke kommer på.
Dette dukker også opp i en del andre begreper, som _étale cohomology_.

**Quadric, cubic, quartic og så videre:**
Der disse ordene er substantiver, er standarden på norsk er å bruke _kvadrikk, kubikk, kvartikk_. Jeg har hørt folk bruke _sekstikk_ og _oktikk_ også. For å fylle ut listen foreslår jeg _kvintikk, septikk, nonikk, desikk_.

**Algebrogeometric/algebro-geometric:**
Jeg foreslår _algebrogeometrisk_ som norsk oversettelse.

**Andre ord:**
(bokmål, nynorsk, engelsk)

- [x] dominant, dominant, dominant
- [x] ramifisert, ramifisert, ramified
- [x] uramifisert, uramifisert, unramified
- [x] knippifisere, knippifisere, sheafify
- [x] kategorifisere, kategorifisere, categorify 
- [x] kvasikompakt, kvasikompakt, quasicompact 
- [x] separert, separert, separated
- [x] perverst knippe, perverst knippe, perverse sheaf
- [x] koggergrassmann, koggergrassmann, quiver Grassmannian
- [x] koggervarietet, koggervarietet, quiver variety
- [x] hilbertskjema, hilbertskjema, Hilbert scheme
- [x] kvot-skjema, kvot-skjema, Quot scheme
- [x] insidens, insidens, incidence
- [x] insidenskorrespondanse, insidenskorrespondanse, incidence correspondence
- [x] chernklasse, chernklasse, Chern class
- [x] segreklasse, segreklasse, Segre class
- [x] chowring, chowring, Chow ring
- [x] kohomologiring, kohomologiring, cohomology ring
- [x] coxring, coxring, Cox ring
- [x] som er synonymt med
- [x] total koordinatring, total koordinatring, total coordinate ring
- [x] divisor, divisor, divisor
- [x] weildivisor, weildivisor, Weil divisor
- [x] cartierdivisor, cartierdivisor, Cartier divisor
- [x] klassegruppe, klassegruppe, class group
- [x] skrikfunktor, skrikfunktor, shriek functor
- [x] nakajimakoggervarietet, nakajimakoggervarietet, Nakajima quiver variety
- [x] vegg-og-rom-struktur, vegg-og-rom-struktur, wall-and-chamber structure
- [x] ren, rein, pure, "I sammenhenger som: «of pure dimension n»."
- [x] dolbeaultkohomologi, dolbeaultkohomologi, Dolbeault cohomology
- [x] de Rham-kohomologi, de Rham-kohomologi, de Rham cohomology
- [x] (eller kanskje derhamkohomologi, ...?)
- [x] čechkohomologi<br>cechkohomologi, čechkohomologi<br>cechkohomologi, Čech cohomology
- [x] l-adisk kohomologi, l-adisk kohomologi, l-adic cohomology 
- [x] hochschildhomologi, hochschildhomologi, Hochschild homology
- [x] hochschildkohomologi, hochschildkohomologi, Hochschild cohomology
- [x] krystallinsk, krystallinsk, crystalline
- [x] derivator, derivator, derivator

(De fire neste er om skjemaer.):

- [x] hel, heil, integral 
- [x] regulær, regulær, regular 
- [x] faktoriell, faktoriell, factorial, "Ordklasse: adjektiv"
- [x] lokalt factoriell, lokalt faktoriell, locally factorial, "Ordklasse: adjektiv"

Redigert: Jeg oppdaget at jeg ikke hadde ført oppslagsordene etter retningslinjene.
Ellers har jeg kommet på en del andre termer som også burde være med. (Blant annen noen veldig sentrale, som "ample".) Burde jeg lage en ny tråd for å diskutere dem? Jeg ser ikke noen retningslinjer for dette.

**Comment by johahaug** [comment]
Takk for mange gode innspill! Skriver du opp navn og eventuelt institusjonstilhørighet, så fører jeg deg opp på lista over bidragsytere?

Flere av oss som jobber med å følge opp innspillene som kommer inn, har litt travle tider akkurat nå. Derfor kan det nok ta noe tid å få alle oversettelsene ferdigverifisert, men det vil tas tak i så fort som mulig. 

Jeg foreslår at du åpner en ny tråd for å legge inn flere termer, siden det da ofte blir litt lettere å holde oversikt. Samtidig er ikke dette veldig viktig, og det fungerer også om du legger dem inn som kommentar i denne tråden.

**Comment by sorengam** [comment]
Takk for det!

Jeg heter Søren Gammelgaard og er stipendiat i Oxford. Men jeg tok bachelor- og mastergrad i Oslo.

Noen av forslagene mine er mer kontroversielle enn andre (for eksempel _hel_ som oversettelse av _integral_ om skjemaer.) Så det er fint å få litt diskusjon om dem.

**Comment by bervinator** [comment]
Hei Søren.
Jeg har tatt en titt på termene du foreslår (også fra #78 ). Jeg beklager sen oppfølging.
Vi setter stor pris på en stor tilførsel av termer fra et fagfelt som er underrepresentert i ordlisten. Det kommer også tydelig frem at du viser stort hensyn til språket!

For øyeblikket betrakter jeg 170 termer som klare for verifisering av prosjektgruppen. Vårt neste møte blir dessverre ikke før til høsten, men vi arbeider aktivt med utbedring av ordlisten fra og med den tid. 

Det gjenstår i underkant av 90 ord jeg tenker å se enda nærmere på. Et stort flertall av disse er vel så gode som de beste 170, men enkelte småting må sjekkes (for eksempel at de går overens med våre konvensjoner). Det er god grunn til å tro at også disse 90 termene går gjennom verifiseringsprosessen i høst.

Jeg har tatt meg friheten til å tilføye følgende termer:
kategorifisering
dekategorifisering
dekategorifisere
frobeniusendomorfi/frobeniushomomorfi (spesielt for ringer med positiv karakteristikk, hvor termen homomorfi foretrekkes over morfi)
veroneseimbedding

Jeg har kun to spørsmål så langt (flere kan komme på sikt).

Har du andre eksempler på hvor "pure" brukes enn "pure dimension"?

Du foreslår både dedekindområde og dedekinddomene som synonyme oversettelser av "Dedekind domain". Om oversettelsen skal følge samme mønster som lignende termer i ordlisten (entydig faktoriseringsområde, euklidsk område, heltallsområde/integritetsområde, hovedidealområde), blir det mest nærliggende å velge kun førstnevnte. Er det i orden om vi gjør det slik?

**Comment by sorengam** [comment]
Om "pure": Det brukes for eksempel i sammenhengen "pure transcendental field extension", som jeg nok vil oversette til _ren transcendental kroppsutvidelse_. Ellers har vi jo begrepet "pure mathematics"
Jeg liker bedre å skrive "transcendent" enn "transendent", selv om det er det siste som står i ordlisten. Men ordbok.uib.no godkjenner begge alternativene.

Jeg er enig i at dedekindområde er å foretrekke, så for min del kan det stå alene. (Men jeg har hørt folk si "dedekinddomene", og tror jeg har brukt det selv også.)

Til sist ser jeg at et temmelig viktig ord som burde være i ordlisten mangler, så jeg foreslår det her:

matematikk, matematikk, mathematics

Og da kan vi jo også ta med

matte, matte, maths, "Uformell kortform av _matematikk_. Nordamerikansk engelsk bruker _math_."

**Comment by bervinator** [comment]
Du har gode grunner til å foretrekke å skrive transcendent med c. Det ser nemlig ut til at både [NAOB](https://www.naob.no/ordbok/transcendent) og [SNL](https://snl.no/transcendent) foretrekker denne formen. Om jeg søker etter ordene transcendent og transendent i norske mattematikkbøker på [Bokhylla](https://www.nb.no/search?q=transcendent&mediatype=b%C3%B8ker&literaryform=Faglitteratur&ddc=51&languages=nob), gir førstnevnte 25 treff mot ni på sistnevnte. Jeg skal diskutere dette med mine medarbeidere.

Som du sier burde vi ta med termene matematikk, matte, ren matematikk, anvendt matematikk, diskret matematikk osv. Disse blir utvilsomt verifisert til høsten :)

**Comment by sorengam** [comment]
En kommentar om _l-adisk kohomologi_: Det er ganske vanlig i løpende tekst å bruke en "løkkeskrift-l", og altså skrive _ℓ-adic cohomology_. (Symbolet finnes i Unicode, på kodepunkt U+2113.) Det er kanskje verdt å føre opp begge varianter?

**Comment by bervinator** [comment]
Selv foretrekker jeg ℓ i løkkeskrift, siden liten l kan veldig lett forveksles med stor I. 
Jeg tviler også at ℓ kan forveksles med en annen bokstav. Dessuten burde vi prøve å legge bruke terminologi og symboler som gjenspeiler utstrakt bruk i fagmiljøene.

**Comment by sorengam** [comment]
Hm, jeg lurer på om det er en misforståelse her? Jeg mente at det er vanlig i trykte og digitale tekster å bruke "ℓ-adic cohomology" i stedet for "l-adic cohomology" - uttalen er selvfølgelig lik. Dette gjøres f.eks. på [nLab](https://ncatlab.org/nlab/show/%E2%84%93-adic+cohomology) og [Wikipedia](https://en.wikipedia.org/wiki/%C3%89tale_cohomology#%E2%84%93-adic_cohomology_groups).

**Comment by bervinator** [comment]
Jeg tror ikke at jeg misforsto, men jeg tok meg kanskje ikke tiden til å formulere meg godt nok.
Forslaget mitt er å føre opp termen "ℓ-adic cohomology" med ℓ i løkkeskrift, siden (som du har poengtert og understrekt) denne bruken er foretrukken av mange. Vi kan i såfall formulere en merknad hvor "l-adic cohomology" nevnes. 

Dessuten vil jeg skille liten L skilles fra stor i. 
Når vi kompletterer en generell ring R i idealet I (stor i), kan vi fint snakke om I-adisk topologi osv. Det er ikke mange piksler som skiller stor i fra liten L, og det er uønskelig at disse forveksles.

Er det greit for deg om "l-adic cohomology" havner i merknaden, eller foretrekker du den likestilt med "ℓ-adic cohomology"?

**Comment by sorengam** [comment]
Ah, da er det jeg som har misforstått. Beklager! 

Jeg tror jeg vil foretrekke at "ℓ-adic cohomology" og "l-adic cohomology" (liten L) likestilles, mest fordi det da er enklere å søke i ordlisten. (Med mindre søkefunksjonen klarer å omdirigere "l-adic" til "l-adic"?) 

Så kan man jo skrive en merknad om at "ℓ-adic" foretrekkes på systemer som kan skille mellom de to symbolene.

**Comment by bervinator** [comment]
Her kommer du med et viktig poeng. Søkbarhet er jo sentralt når det kommer til brukervennlighet.

Vi har tidligere sørget for at søkefunksjonen overser aksenter og diakritiske tegn når brukeren søker etter termer. [Den samme algoritmen](https://github.com/jfremstad/matematisk_ordliste/blob/master/nettside/js/accent-neutralise.js) skiller heller ikke mellom tankestrek og bindestrek, som sørger for at brukeren får treff på termer som "Newton–Cotes' rule" selv om egennavnene skilles med bindestrek (fremfor tankestrek) i søket. 

Ved å legge til én linje kode i denne filen, kan vi få søkealgoritmen til å betrakte ℓ som l. Det er derfor ingen fare om vi kun fører opp "l-adic cohomology", sett bort ifra at denne bruken er relativt uvanlig. Om vi derimot kun fører opp "ℓ-adic cohomology", tror jeg det må mange flere linjer til for å fange dette opp i søk etter "l-adic cohomology". Jeg endrer derfor standpunktet mitt, og sier meg enig i at termene "l-adic cohomology" og "ℓ-adic cohomology" burde likestilles.

Sortering er en annen problemstilling. Om vi benytter symbolet ℓ, må vi også sørge for at den betraktes som l i sorteringsalgoritmen vår. Vi har tidligere sørget for at æ, ø og å sorteres riktig på norsk, så jeg utelukker ikke at vi kan klare dette. 
Jeg mener likevel at dette ikke er nødvendig. Ettersom ℓ burde komme etter l i sorteringen, føres termen opp som følger:
> l-adisk kohomologi / ℓ-adisk kohomologi, l-adisk kohomologi / ℓ-adisk kohomologi, l-adic cohomology / ℓ-adic cohomology

Om termen føres opp slik, gjør det ingen forskjell hvordan ℓ sorteres, og det sparer oss for noe arbeid. 

Jeg foreslår derfor at vi fører opp termen som over. Jeg enig i ditt forslag om merknad, som i praksis kan se slik ut:
>  Både l-adisk kohomologi og ℓ-adisk kohomologi forekommer i bruk, men ℓ-adisk kohomologi anbefales så lenge symbolet ℓ er tilgjengelig.

Høres dette greit ut?

**Comment by sorengam** [comment]
Takk, det ser fint ut!

**Comment by bervinator** [comment]
Det virker som at nesten alle ordene ligger i ordlisten. Unntakene er på vei til prosjektgruppen for verifisering. Jeg lukker denne tråden, men åpner en ny tråd om nødvendig.
Igjen mange takk for bokstavelig talt hundrevis av gode forslag!
