### ISSUE TITLE
Diametralt motsatt

### ISSUE THREAD

**Issue by robinfissum** [jfremstad/matematisk_ordliste#79]
Hei! Hva med å supplere oversettelsen av "Antipodal points" med " Diametralt motsatte punkter" ? :)

**Comment by bervinator** [comment]
Hei.
Mange takk for innspillet!
Det virker som at diametralt motsatt (evt. også diametralt motstående) er mye brukt i en rekke svært troverdige kilder. For eksempel:
[NAOB](https://www.naob.no/ordbok/diametral?elementRefid=52856418)
[SNL](https://snl.no/diameter)
[Lindstrøms Kalkulus](https://www.nb.no/items/27affa053d84949c98ff649f2c728ac3?page=191&searchText=diametralt%20motsatt)
[Denne topologiboken](https://www.nb.no/items/a67ffeadbdcb1a25cc699e46f1836c26?page=0&searchText=diametralt%20motsatt)
[Abelkomitéens begrunnelse da de utdelte prisen til John Milnor](https://www.abelprisen.no/c53071/binfil/download.php?tid=53563)
[Dette kompendiet](https://www.uio.no/studier/emner/matnat/math/nedlagte-emner/MAT0100V/h14/kompendium1.pdf)
Personlig synes jeg derfor at det blir riktig å legge inn denne oversettelsen som synonym.

**Comment by johahaug** [comment]
Dette virker etter min mening som et godt forslag, spesielt siden denne oversettelsen egentlig gir bedre innblikk i meningsinnholdet. Jeg vil støtte å endre oppslagsordene _antipodalt punkt_ og _antipode_ til: 

```
antipodalt punkt / diametralt motsatt punkt,antipodalt punkt / diametralt motsett punkt,antipodal point,"Synonym: antipode"

antipode,antipode,antipode,"Synonym: antipodalt punkt / diametralt motsatt punkt".
```

**Comment by bervinator** [comment]
Jeg stiller meg bak Johannes forslag.

**Comment by johahaug** [comment]
Siden det virker som om det er enighet om dette, lukker jeg tråden og legger inn dette i neste verifiseringsrunde. Bra innspill, @robinfissum!
