### ISSUE TITLE
Limit point, cluster point, accumulation point

### ISSUE THREAD

**Issue by MortGron** [jfremstad/matematisk_ordliste#80]
I topologi brukes ofte begrepene "limit point", "cluster point" og "accumulation point" synonymt, men i ordlisten er "limit point" oversatt med "grensepunkt", "accumulation point" oversatt med "opphopningspunkt" og "cluster point" har ingen oversettelse.  Burde ikke alle disse stå oppført med samme oversettelse for deres betydning innen topologi?

**Comment by bervinator** [comment]
Hei.
Som du sier er det god grunn til å påpeke at "limit point" og "accumulation point" ofte brukes synonymt på engelsk, spesielt innen topologi. Dette gjøres blant annet av Munkres, som også tar med  "cluster point" som synonym.
Dessverre finner jeg ikke en norsk lærebok hvor termene grensepunkt og opphopningspunkt brukes synonymt. Det ser nemlig ut til å gjelde samtlige av [disse](https://www.nb.no/search?q=opphopningspunkt&mediatype=bøker&ddc=51).
Det er derimot kun _Topologi_ av P. Holm og J. Reed som er en topologibok blant disse. I analysen ser jeg for meg at de ikke brukes synonymt, som kan ha bidratt til at jeg ikke finner kilder som benytter ordene i samme betydning som Munkres.

Jeg er ikke kjent med en anerkjent oversettelse av "cluster point" på norsk. Klyngepunkt kan være en mulighet ([klyngeanalyse](https://www.naob.no/ordbok/klyngeanalyse) er en etablert oversettelse av "cluster anaylsis" fra statistikken), men det er ikke godt å si om noen sier dette. 


Jeg skal utarbeide er endringsforslag av ordlisten slik at i det minste kommer frem at grensepunkt og opphopningspunkt ofte brukes om samme begrep. Du hører fra meg. :)

**Comment by bervinator** [comment]
Hei igjen.
Vi har kommet frem til følgene forslag: Vi fører opp termene:
grensepunkt - limit point
opphopningspunkt - accumulation point
klyngepunkt - cluster point 
med merknader om at disse kan brukes synonymt, men kun i enkelte sammenhenger. 
Virker dette greit for deg?

**Comment by bervinator** [comment]
Disse termene har blitt diskutert og er nå på vei inn i ordlisten.
Mange takk for innspill!
Kommenter gjerne navn og evt. utdanningsinstitusjon, slik at vi kan legge deg til som bidragsyter.

**Comment by MortGron** [comment]
Dette høres veldig bra ut, og takk for gjennomgangen. Mitt navn er Morten Grønbech, og min daværende utdanningsinstitusjon var NTNU.
