### ISSUE TITLE
Totally disconnected og Nowhere dense

### ISSUE THREAD

**Issue by robinfissum** [jfremstad/matematisk_ordliste#81]
Jeg har disse to forslagene fra topologi: 

Totally disconnected/
Totalt usammenhengende/ 
Totalt usamanhengande:

A topological space is totally disconnected if its components are its singeltons.

Og: 

Nowhere dense/ingensteds tett/ Ingenstad tett: 

A subspace H of a space T is nowhere dense in T if the interior of the closure of H is empty.

:)

**Comment by johahaug** [comment]
Jeg synes disse oversettelsene virker uproblematiske. Spesielt for den første framstår dette for meg som det eneste aktuelle alternativet til oversettelse. Også den siste virker god, og brukes av seriøse kilder som f.eks. [denne](https://www.uio.no/studier/emner/matnat/math/MAT2400/v12/Cantor.pdf). 

Bare for at det skal bli helt presist: Nynorskformen må også starte med liten forbokstav.

**Comment by bervinator** [comment]
Disse termene er på vei inn i ordlisten. Mange takk for innspill!
