### ISSUE TITLE
Pairing

### ISSUE THREAD

**Issue by andreas1729** [jfremstad/matematisk_ordliste#82]
**Forslag til oversettelse**

Forslag ønskes.

**Kommentar**

Bilinear pairing, Tate pairing, Weil pairing. Hva sier dere som underviser f.eks. kryptografi?

**Comment by bervinator** [comment]
Hei og beklager sen tilbakemelding.
Her tenker jeg at bilineær paring, tateparing og weilparing burde være greie.
Jeg kan foreslå disse i neste verifiseringsrunde. De vil dermed bli vurdert og diskutert av medlemmene i prosjektgruppen.

**Comment by bervinator** [comment]
Disse termene har blitt diskutert og er nå på vei inn i ordlisten.
Mange takk for innspill!
Kommenter gjerne navn og evt. utdanningsinstitusjon, slik at vi kan legge deg til som bidragsyter.
