### ISSUE TITLE
Gratis

### ISSUE THREAD

**Issue by treeininga** [jfremstad/matematisk_ordliste#84]
Kanskje dette er eit dårleg forslag, men det kan uansett bli ein morosam diskusjon. Forslaget er å kalle ting som _free group, free category, free fucntor_  osv for gratis gruppe, gratis kategori og gratis funktor. Argumentasjonen for forslaget er at for eksempel ei gratis gruppe G(S) frå eit set S, er gruppa som innheld S med minst mulig arbeid. Ein kan seie ein får gruppa servert gratis ut frå S. Eg ser heller ikkje kvifor å bruke fri som i at ei gruppe er "fri som fuglen" gir mykje meining. Kva tykkjer dykk?

**Comment by sorengam** [comment]
Interessant forslag, men jeg er nok ikke enig.

Den første grunnen er at ordbruken _fri (gruppe/kategori/funktor/modul)_ er godt innarbeidet på norsk. I tillegg er det den mest innlysende oversettelsen av _free_. 

Ellers synes jeg egentlig ordet passer fint, om man tenker på _fri_ i betydningen "det stilles ikke noen krav eller betingelser". Det passer jo fint om fuglen, og også om en fri gruppe - en fri gruppe har nettopp ingen relasjoner mellom elementene, utover de som gruppeaksiomene krever.

**Comment by johahaug** [comment]
Jeg stiller meg egentlig bak alt @sorengam skriver her - artig forslag, men jeg synes også at fri er best. I en fri gruppe er det så få "betingelser" (relasjoner som må oppfylles) som mulig, og jeg synes begrepet fri passer godt for å beskrive dette. Man kan altså tenke på "fri som fuglen" i den forstand at det ikke stilles noen krav. Utbredelse og paralleller til andre språk framstår for meg også som tungtveiende argumenter.

**Comment by simonfoldvik** [comment]
Jeg er enig i at argumentasjonen til @sorengam er konkluderende og lukker tråden.
