### ISSUE TITLE
Grafteori

### ISSUE THREAD

**Issue by markusvhagen** [jfremstad/matematisk_ordliste#86]
Jeg ser ordboka mangler en del norsk termer i grafteori. Her er noen forslag.

**Forslag:** komplett graf, komplett graf, complete graph
**Merknad:** Et annet alternativ kunne også vært fullstendig graf, men det vil være å vike litt fra andre norske oversettelser. Komplett graf blir for eksempel brukt av Roger Antonsen her: <https://www.uio.no/studier/emner/matnat/math/nedlagte-emner/MAT1030/v09/undervisningsmateriale/kompendium.pdf>

**Forslag:** todelt graf, todelt graf, bipartite graph 
**Merknad:** Dette er en oversettelse jeg er usikker på. I følge wikipedia sier man todelt graf på dansk og bipartit graf på svensk. Jeg er personlig mest tilhenger av den danske versjonen.

**Forslag:** koblingsmatrise, koblingsmatrise, adjacency matrix
**Merknad:** Roger Antonsen bruker også denne oversettelsen i samme linken som over. Før jeg kom over pdf-en til Antonsen tenkte jeg selv en annen mulig oversettelse kunne være nabomatrise.

**Andre forslag:**
vektet graf, vektet graf, weigthed graph
simpel graf, simpel graf, simple graph
krets, krets, circuit
sti, sti, path
vei, veg, path
euler(sti/vei), eulersti(sti/veg), Euler path
hamilton(sti/vei), hamilton(sti/veg), Hamilton path
eulersk graf, eulersk graf, Eulerian graph
hamiltonsk graf, hamitonsk graf, Hamiltonian graph
plangraf, plangraf, planar graph

**Comment by bervinator** [comment]
Hei
Takk for du viser til Antonsens forelesningsnotater. Vi arbeider for øyeblikket med termer fra grafteorien, og jeg kom ikke over dette notatet da jeg var på utkikk etter troverdige kilder. 

Vi har blant annet oversatt _adjencency matrix_ nabomatrise. Siden disse gir omtrent like mange treff som koblingsmatrise på [Bokhylla](bokhylla.no) ser det ut til at vi burde sidestille disse.

Jeg skal ta en ny titt på disse termene i lys av dine forslag :)

**Comment by markusvhagen** [comment]
Mulig du vet det allerede, men Antonsen har også skrevet en norsk bok (og der et to kapitler om grafteori). Den heter _Logiske metoder - kunsten å tenke abstrakt og matematisk_.

**Comment by bervinator** [comment]
Disse termene er på vei til prosjektgruppen for verifisering. Jeg lukker denne tråden, men åpner en ny tråd om nødvendig. Mange takk for forslag!
