### ISSUE TITLE
Logisk proposisjon - Antesedent/konsekvent

### ISSUE THREAD

**Issue by ninist** [jfremstad/matematisk_ordliste#87]
**Forslag:**
antesedent,antesedent,antecedent
konsekvent,konsekvent,consequent

**Merknad:**
Delene i en logisk proposisjon.

```
antecedent \Rightarrow consequent
```
Jeg har sett antesedent brukt på norsk (både bokmål og nynorsk), men jeg er mindre sikker på konsekvent. 
Svensk Wikipedia bruker disse to (men som antecedent).

**Comment by bervinator** [comment]
Hei
Takk for innspill! Dette er ord vi må se til å få inn i ordlisten.

Hvor har du kommet over ordene antesedent og konsekvent? Oppslagsverkene vi bruker har valgt andre varianter.
SNL omtaler disse som antecedent og konsekvens [her](https://snl.no/antecedent). NAOB bruker antesedent som en variant [her](https://www.naob.no/ordbok/antecedent), men skriver konsekvens med s. 

For min del foretrekker jeg antesedent over antecedent, men finnes det noen kilder som bruker denne varianten?

**Comment by ninist** [comment]
Jeg har sett antesedent brukt med S i Norsk referansegrammatikk, samt i Norsk generativ syntaks (Åfarli og Eide).
Bruken her er imidlertid i en litt annen sammenheng enn logikk.

Jeg har ikke sett konsekvent, og jeg har heller ikke selv en sterk formening om foretrukken form her. Jeg legger bare merke til at engelsk ikke har valgt "consequence".

**Comment by johahaug** [comment]
Jeg vil også foretrekke skrivemåten antesedent. En mulighet kan være å føre opp denne som oppslagsord, men med merknad om at antecedent også er mulig? Jeg tenker da på en merknad av typen som brukes f.eks. på oppslaget "separerende transendensbasis" som er en del av den nåværende ordlista. 

(Forresten, og ikke egentlig relatert til denne tråden: Jeg ser at det ikke er ført opp noen tilsvarende merknad i oppslagene for "transendent funksjon" og "transendent tall". Det bør kanskje med for at merknadene skal være konsekvente?)

Ellers: Tusen takk for mange innspill, @ninist! Legg gjerne igjen fullt navn og eventuell institusjonstilhørighet, så blir du lagt til i listen over bidragsytere.

**Comment by bervinator** [comment]
Disse termene har blitt diskutert og er nå på vei inn i ordlisten.
Mange takk for innspill!
Kommenter gjerne navn og evt. utdanningsinstitusjon, slik at vi kan legge deg til som bidragsyter.
