### ISSUE TITLE
Analytic continuation, essential singularity, isolated singularity, (Montel's) normal family, removable singularity, path integral, contour integral, Laurent series, Riemann surface (kompleks analyse)

### ISSUE THREAD

**Issue by StineBerge** [jfremstad/matematisk_ordliste#9]
**Forslag:**

- [ ] analytisk forsettelse, analytisk forsetjing, analytic continuation
- [ ] essensiel singularitet, essensiel singularitet, essential singularity
- [x] isolert singularitet, isolert singularitet, isolated singularity 
- [x] normal familie av funksjoner, normal familie av funksjonar, normal family of functions
- [ ] fjernbar singularitet, fjernbar singularitet, removable singularity
- [ ] stiintegral/ integral over en sti, stiintegral/ integral over ein sti, path integral
- [ ] omrissintegral/konturintegral, omrissintegral/konturintegral, conture integral
- [x] laurentrekke, laurentrekkje, Laurent series
- [x] riemannflate, reimannflate, Riemann surface

**Merknad:**
Foretrekker omrissintegral fremfor konturintegral.

**Comment by bowre** [comment]
Er overrasket over at _essential singularity_ oversettes som _essensiell singularitet_ og ikke som _vesentlig singularitet_ som vi lærte av Waadeland da jeg studerte. Husker også godt at _removable singularity_ ble oversatt til _hevbar singularitet_ (og ikke det direkte-oversatte _fjernbar singularitet_ som her foreslås.

**Comment by johahaug** [comment]
Godt poeng. Noen umiddelbare observasjoner: 

_Essential singularity:_ På bokhylla.no får man 11 treff på _vesentlig singularitet_, mot ingen på _essensiell singularitet_. 

_Removable singularity:_ Tilsvarende gir _hevbar singularitet_ 2 treff (hvorav det ene fra en meget troverdig kilde), mot ingen på _fjernbar singularitet_. 

Dette antyder at oversettelsene @bowre foreslår er de beste. Jeg lar tråden stå åpen litt i tilfelle noen har andre innspill.

**Comment by johahaug** [comment]
Jeg legger inn hevbar singularitet og vesentlig singularitet som forslag som blir tatt med i neste verifiseringsrunde. Tråden kan gjenåpnes dersom noen er uenige.
