### ISSUE TITLE
(relative) efficiency

### ISSUE THREAD

**Issue by ninist** [jfremstad/matematisk_ordliste#92]
**Kommentar**

Relative efficiency, 
Efficient, 
Estimator being more efficient than other estimator.

https://en.wikipedia.org/wiki/Efficiency_(statistics)

**Comment by bervinator** [comment]
Hei,
I [ISIs statistikkordliste](http://isi.cbs.nl/glossary/term1075.htm) oversettes _efficiency_ til effisiens. Selv hadde jeg trodd at effektivitet var fornuftig, men jeg skal forhøre meg med noen fagfolk hva som er best å velge.
Erlend

**Comment by bervinator** [comment]
Jeg finner flere treff med effisiens på [Bokhylla](https://www.nb.no/search?q=effisiens&mediatype=b%C3%B8ker&ddc=51).

**Comment by bervinator** [comment]
Disse termene har blitt diskutert og er nå på vei inn i ordlisten.
Mange takk for innspill!
Kommenter gjerne navn og evt. utdanningsinstitusjon, slik at vi kan legge deg til som bidragsyter.
