### ISSUE TITLE
Z-ratio, t-ratio, ...

### ISSUE THREAD

**Issue by ninist** [jfremstad/matematisk_ordliste#94]
**Kommentar**
Hypotesetester.

**Comment by bervinator** [comment]
I [ISIs ordliste](http://isi.cbs.nl/glossary/bloken00.htm) finner vi oversettelsen t-kvote. Om denne fungerer vil jeg tro at Z-kvote også er rimelig.
Erlend

**Comment by bervinator** [comment]
Disse termene har vært litt vriene. Det er tydeligvis vanligere å si observator enn kvote i denne sammenhengen, selv om kvote helt klart er den beste oversettelsen av "ratio" i denne sammenhengen. Jeg prøver likevel å få disse termene inn i ordlisten. De foreslås på neste møte.
