### ISSUE TITLE
Power; Power curve

### ISSUE THREAD

**Issue by ninist** [jfremstad/matematisk_ordliste#95]
**Forslag:**
teststyrke,teststyrke,power
styrkefunksjon,styrkefunksjon,power curve

**Kommentar:**
Hypotesetester. Termene finnes allerede i ordlisten, men i betydningen potens.

**Comment by bervinator** [comment]
[ISIs ordliste](http://isi.cbs.nl/glossary/term2540.htm) sier seg ganske enig her :)

**Comment by bervinator** [comment]
Disse termene har blitt diskutert og er nå på vei inn i ordlisten.
Mange takk for innspill!
Kommenter gjerne navn og evt. utdanningsinstitusjon, slik at vi kan legge deg til som bidragsyter.
