### ISSUE TITLE
En del andre begreper fra logikk

### ISSUE THREAD

**Issue by ninist** [jfremstad/matematisk_ordliste#96]
Skolemization
Skolem function
Skolem constant
Reification
Reify
Horn clause
Clause
Conjunctive normal form
Satisfiable
Entail

**Comment by bervinator** [comment]
Følgende forslag videresendes til prosjektgruppen:

- skolemisering
- skolemfunksjon
- skolemkonstant
- reifisering
- reifisere
- klausul
- hornklausul
- konjunktiv normalform

 Jeg tviler på at de hindres i sin ferd til ordlisten. Tråden holdes åpen helt til "satisfiable" og "entail" er oversatt. 
Mange takk for forslag!
