### ISSUE TITLE
Consistent estimator, Asymptotically consistent estimator

### ISSUE THREAD

**Issue by ninist** [jfremstad/matematisk_ordliste#97]

**Comment by bervinator** [comment]
[ISIs ordliste](http://isi.cbs.nl/glossary/term733.htm) har oversatt førstnevnte til konsistent estimator.

**Comment by bervinator** [comment]
Disse termene har blitt diskutert og er nå på vei inn i ordlisten.
Mange takk for innspill!
Kommenter gjerne navn og evt. utdanningsinstitusjon, slik at vi kan legge deg til som bidragsyter.
