### ISSUE TITLE
Probability mass function

### ISSUE THREAD

**Issue by ninist** [jfremstad/matematisk_ordliste#98]
**Kommentar**
Ser kun ut til å være oversettelse av density.

**Comment by bervinator** [comment]
Denne må vi få med i ordlisten!
Jeg finner oversettelsen sannsynlighetsmasse i [ISIs ordliste](http://isi.cbs.nl/glossary/term2581.htm).

**Comment by bervinator** [comment]
Denne termen har blitt diskutert og er nå på vei inn i ordlisten.
Mange takk for innspill!
Kommenter gjerne navn og evt. utdanningsinstitusjon, slik at vi kan legge deg til som bidragsyter.
