### ISSUE TITLE
undermatrise og trippelprodukt

### ISSUE THREAD

**Issue by egilkrystad** [jfremstad/matematisk_ordliste#99]
submatrix, undermatrise, undermatrise
triple product, trippelprodukt, trippelprodukt

**Comment by bervinator** [comment]
Hei
Disse termene ser meget rimelige ut. Jeg finner dem i flere lærebøker. De foreslås til neste verifiseringsrunde.
Erlend

**Comment by bervinator** [comment]
Denne termen har blitt diskutert og er nå på vei inn i ordlisten.
Mange takk for innspill!
